// Credits to https://github.com/Snake4life
use rand::random;

pub fn random_name() -> String {
    let rnd_type = rand_max(5);
    let rnd_gender = rand_max(10);

    let gender = match rnd_gender {
        0..5 => NickGender::Female,
        _ => NickGender::Male,
    };

    match rnd_type {
        0 => dwarf(gender),
        1 => barbarian(gender),
        2 => elf(gender),
        3 => bandit(gender),
        4 => demon(),
        _ => goblin(gender),
    }
}

pub enum NickGender {
    Male,
    Female,
}

fn rand_max(max: usize) -> usize {
    (random::<f32>() * max as f32).floor() as usize
}

// consumes string and returns it back
fn make_ascii_title_case(mut s: String) -> String {
    if let Some(r) = s.get_mut(0..1) {
        r.make_ascii_uppercase();
    }

    s
}

pub fn dwarf(gender: NickGender) -> String {
    static NAME1: [&str; 103] = [
        "A", "Ara", "Alfo", "Bari", "Be", "Bo", "Bha", "Bu", "Ba", "Bra", "Bro", "Brou", "Bru",
        "Da", "Dalo", "Dare", "De", "Dhu", "Dho", "Do", "Dora", "Dwo", "Dou", "Duri", "Du", "El",
        "Eri", "Fi", "Fo", "Fo", "Ga", "Gi", "Gla", "Glori", "Go", "Gra", "Gro", "Groo", "Gru",
        "Grou", "Ha", "Ha", "He", "He", "Ho", "Hou", "Hu", "Ja", "Jo", "Ka", "Khe", "Khu", "Khou",
        "Ko", "Ku", "Ki", "Kra", "Kro", "Lo", "Lu", "Lo", "Ma", "Mo", "Mu", "Na", "No", "Nu",
        "Nora", "Nura", "Ne", "No", "O", "Ori", "Rei", "Ra", "Ru", "Sa", "Si", "Sna", "Sko", "Ska",
        "Stro", "The", "Thi", "Tho", "Thra", "Tha", "Tore", "Tha", "Thra", "Thro", "Thu", "Tu",
        "U", "Umi", "Va", "Vo", "Whu", "We", "Wera", "Yu", "Yo", "Ya",
    ];

    static NAME2: [&str; 65] = [
        "b", "br", "dd", "d", "dr", "dm", "dgr", "f", "fr", "gr", "gg", "gh", "gn", "k", "kh",
        "kgr", "kdr", "kk", "kh", "kr", "l", "lg", "lgr", "ldr", "lm", "md", "mn", "m", "mm", "mr",
        "n", "nd", "ndr", "ngr", "nm", "r", "rr", "rgr", "rdr", "rb", "rg", "rn", "rh", "rd", "rm",
        "rs", "rf", "s", "ss", "sdr", "sgr", "st", "str", "t", "tr", "tm", "th", "tdr", "tgr", "v",
        "vr", "z", "zm", "zn", "zz",
    ];

    static NAME3: [&str; 152] = [
        "ac", "aic", "aec", "ec", "eac", "ic", "oc", "oic", "ouc", "ack", "aeck", "eck", "eack",
        "ick", "ock", "oick", "ouck", "uck", "uc", "ad", "aed", "ed", "ead", "id", "od", "oid",
        "oud", "ud", "uid", "ag", "aeg", "eg", "eag", "ig", "og", "oug", "ug", "ak", "aek", "ek",
        "eak", "ik", "ok", "oki", "uk", "uik", "ouk", "uki", "al", "ael", "el", "eal", "il", "ol",
        "oli", "olin", "olim", "olir", "oul", "ul", "uli", "ulim", "ulir", "uil", "am", "ami",
        "amli", "amri", "aem", "em", "eam", "im", "om", "omli", "omri", "omi", "oum", "um", "umi",
        "umir", "umin", "umli", "umlir", "umlin", "umri", "an", "aen", "en", "ean", "in", "on",
        "onlim", "onlir", "oun", "un", "unli", "unri", "ar", "arlum", "arlun", "arlug", "arlig",
        "aer", "er", "erlum", "erlun", "erlug", "erlig", "ear", "ir", "irlum", "irlun", "or",
        "orli", "orlim", "orlum", "orlun", "orlig", "orlug", "oir", "our", "ur", "uri", "urim",
        "urum", "us", "as", "ous", "aes", "eas", "at", "atir", "atum", "atin", "aet", "et", "eat",
        "it", "ot", "otir", "atin", "otum", "out", "ut", "ath", "aeth", "eth", "eath", "ith",
        "oth", "outh", "uth",
    ];

    static NAME4: [&str; 103] = [
        "A", "Ara", "Alfo", "Bari", "Be", "Bo", "Bha", "Bu", "Ba", "Bra", "Bro", "Brou", "Bru",
        "Da", "Dalo", "Dare", "De", "Dhu", "Dho", "Do", "Dora", "Dwo", "Dou", "Duri", "Du", "El",
        "Eri", "Fi", "Fo", "Fo", "Ga", "Gi", "Gla", "Glori", "Go", "Gra", "Gro", "Groo", "Gru",
        "Grou", "Ha", "Ha", "He", "He", "Ho", "Hou", "Hu", "Ja", "Jo", "Ka", "Khe", "Khu", "Khou",
        "Ko", "Ku", "Ki", "Kra", "Kro", "Lo", "Lu", "Lo", "Ma", "Mo", "Mu", "Na", "No", "Nu",
        "Nora", "Nura", "Ne", "No", "O", "Ori", "Rei", "Ra", "Ru", "Sa", "Si", "Sna", "Sko", "Ska",
        "Stro", "The", "Thi", "Tho", "Thra", "Tha", "Tore", "Tha", "Thra", "Thro", "Thu", "Tu",
        "U", "Umi", "Va", "Vo", "Whu", "We", "Wera", "Yu", "Yo", "Ya",
    ];

    static NAME5: [&str; 70] = [
        "b", "br", "dd", "d", "dr", "dm", "dgr", "dw", "f", "fr", "gr", "gg", "gh", "gn", "k",
        "kh", "kgr", "kdr", "kk", "kw", "kh", "kr", "l", "lg", "lgr", "ldr", "lm", "md", "mw",
        "mn", "m", "mm", "mr", "n", "nd", "ndr", "nw", "ngr", "nm", "r", "rr", "rgr", "rdr", "rb",
        "rg", "rn", "rh", "rd", "rm", "rs", "rf", "s", "ss", "sdr", "sgr", "st", "str", "t", "tr",
        "tm", "th", "tdr", "tgr", "v", "vr", "w", "z", "zm", "zn", "zz",
    ];

    static NAME6: [&str; 447] = [
        "abelle", "aebelle", "ebelle", "ibelle", "obelle", "ubelle", "alyn", "aelyn", "elyn",
        "ealyn", "ilyn", "olyn", "oulyn", "ulyn", "uilyn", "alynn", "aelynn", "elynn", "ealynn",
        "ilynn", "olynn", "oulynn", "ulynn", "uilynn", "abelyn", "aebelyn", "ebelyn", "eabelyn",
        "ibelyn", "obelyn", "oubelyn", "ubelyn", "uibelyn", "abelynn", "aebelynn", "ebelynn",
        "eabelynn", "ibelynn", "obelynn", "oubelynn", "ubelynn", "uibelyn", "anelyn", "aenelyn",
        "enelyn", "eanelyn", "inelyn", "onelyn", "ounelyn", "unelyn", "uinelyn", "anelynn",
        "aenelynn", "enelynn", "eanelynn", "inelynn", "onelynn", "ounelynn", "unelynn", "uinelynn",
        "agit", "aegit", "egit", "eagit", "igit", "ogit", "ugit", "uigit", "agith", "aegith",
        "egith", "eagith", "igith", "ogith", "ugith", "uigith", "irgit", "irgith", "uirgit",
        "uirgith", "airgit", "airgith", "arika", "aerika", "erika", "earika", "irika", "orika",
        "urika", "atain", "aetain", "etain", "eatain", "itain", "otain", "utain", "ataine",
        "aetaine", "etaine", "eataine", "itaine", "otaine", "utaine", "ahilda", "aehilda",
        "ehilda", "eahilda", "ohilda", "ihilda", "uhilda", "ahulda", "aehulda", "ehulda",
        "eahulda", "ohulda", "ihulda", "uhulda", "agar", "aegar", "egar", "eagar", "igar", "ogar",
        "ugar", "agaer", "egaer", "igaer", "ogaer", "ugaer", "atrud", "aetrud", "etrud", "eatrud",
        "itrud", "otrud", "utrud", "atrude", "aetrude", "etrude", "eatrude", "itrude", "otrude",
        "utrude", "ada", "aeda", "eda", "eada", "ida", "oda", "uda", "alda", "aelda", "elda",
        "ealda", "ilda", "olda", "oulda", "ulda", "alin", "aelin", "elin", "ealin", "ilin", "olin",
        "oulin", "ulin", "aline", "aeline", "eline", "ealine", "iline", "oline", "ouline", "uline",
        "atalin", "aetalin", "etalin", "eatalin", "italin", "otalin", "outalin", "utalin",
        "atalyn", "aetalyn", "etalyn", "eatalyn", "italyn", "otalyn", "outalyn", "utalyn",
        "atelin", "aetelin", "etelin", "eatelin", "itelin", "otelin", "outelin", "utelin",
        "atelyn", "aetelyn", "etelyn", "eatelyn", "itelyn", "otelyn", "outelyn", "utelyn",
        "angrid", "aengrid", "engrid", "eangrid", "ingrid", "ongrid", "oungrid", "ungrid", "ani",
        "aeni", "eni", "eani", "ini", "oni", "ouni", "uni", "ana", "aena", "ena", "eana", "ina",
        "ona", "ouna", "una", "alsia", "aelsia", "elsia", "ealsia", "ilsia", "olsia", "oulsia",
        "ulsia", "ala", "aela", "ela", "eala", "ila", "ola", "oula", "ula", "abella", "aebella",
        "ebella", "eabella", "ibella", "obella", "oubella", "ubella", "abela", "aebela", "ebela",
        "eabela", "ibela", "obela", "oubela", "ubela", "astr", "aestr", "estr", "eastr", "istr",
        "ostr", "oustr", "ustr", "abo", "aebo", "ebo", "eabo", "ibo", "obo", "oubo", "ubo",
        "abena", "aebena", "ebena", "eabena", "ibena", "obena", "oubena", "ubena", "abera",
        "aebera", "ebera", "eabera", "ibera", "obera", "oubera", "ubera", "adeth", "aedeth",
        "edeth", "eadeth", "ideth", "odeth", "oudeth", "udeth", "adrid", "aedrid", "edrid",
        "eadrid", "idrid", "odrid", "oudrid", "udrid", "abyrn", "aebyrn", "ebyrn", "eabyrn",
        "ibyrn", "obyrn", "oubyrn", "ubyrn", "agrett", "aegrett", "egrett", "eagrett", "igrett",
        "ogrett", "ougrett", "ugrett", "agret", "aegret", "egret", "eagret", "igret", "ogret",
        "ougret", "ugret", "asli", "aesli", "esli", "easli", "isli", "osli", "ousli", "usli",
        "ahilda", "aehilda", "ehilda", "eahilda", "ihilda", "ohilda", "ouhilda", "uhilda",
        "ahilde", "aehilde", "ehilde", "eahilde", "ihilde", "ohilde", "ouhilde", "uhilde", "aginn",
        "aeginn", "eginn", "eaginn", "iginn", "oginn", "ouginn", "uginn", "amora", "aemora",
        "emora", "eamora", "imora", "omora", "oumora", "umora", "alydd", "aelydd", "elydd",
        "ealydd", "ilydd", "olydd", "oulydd", "ulydd", "akara", "aekara", "ekara", "eakara",
        "ikara", "okara", "oukara", "ukara", "aren", "aeren", "eren", "earen", "iren", "oren",
        "ouren", "uren", "arra", "aerra", "erra", "earra", "irra", "orra", "ourra", "urra", "are",
        "aere", "ere", "eare", "ire", "ore", "oure", "ure", "awynn", "aewynn", "ewynn", "eawynn",
        "iwynn", "owynn", "ouwynn", "uwynn", "atryd", "aetryd", "etryd", "eatryd", "itryd",
        "otryd", "outryd", "utryd", "athra", "aethra", "ethra", "eathra", "ithra", "othra",
        "outhra", "uthra", "aserd", "aeserd", "eserd", "easerd", "iserd", "oserd", "ouserd",
        "userd", "tryd",
    ];

    static NAME7: [&str; 121] = [
        "Ale", "Amber", "Anvil", "Ash", "Axe", "Barbed", "Barrel", "Battle", "Beast", "Bone",
        "Beryl", "Bitter", "Black", "Blazing", "Blessed", "Blood", "Blunt", "Bone", "Bottle",
        "Boulder", "Brew", "Brick", "Bright", "Bristle", "Broad", "Bronze", "Brown", "Cave",
        "Cask", "Chain", "Crag", "Chaos", "Coal", "Coin", "Copper", "Dark", "Deep", "Dim",
        "Dragon", "Drake", "Dusk", "Earth", "Ember", "Fiery", "Flint", "Flask", "Flint", "Flat",
        "Forge", "Frost", "Giant", "Gold", "Golden", "Granite", "Gravel", "Gray", "Great", "Grey",
        "Grim", "Grumble", "Hammer", "Hard", "Heavy", "Hill", "Honor", "Horn", "Ice", "Ingot",
        "Iron", "Jade", "Keg", "Kobold", "Krag", "Lead", "Large", "Lava", "Leather", "Light",
        "Long", "Marble", "Magma", "Merry", "Metal", "Mithril", "Mine", "Mountain", "Mud", "Night",
        "Noble", "Oak", "Oaken", "Onyx", "Opal", "Ore", "Orc", "Plate", "Pebble", "Red", "Rune",
        "Ruby", "Sapphire", "Shadow", "Shatter", "Smelt", "Silver", "Snow", "Steel", "Storm",
        "Strong", "Troll", "Thunder", "Twilight", "Treasure", "Under", "War", "Warm", "Whit",
        "Wind", "Wold", "Wraith", "Wyvern",
    ];

    static NAME8: [&str; 73] = [
        "arm", "armour", "axe", "back", "bane", "beard", "basher", "belly", "belt", "bender",
        "blade", "born", "bow", "braid", "braids", "branch", "brand", "breaker", "brew", "brewer",
        "bringer", "brow", "buckle", "buster", "chest", "chin", "cloak", "coat", "delver",
        "digger", "foot", "fall", "fury", "finger", "flayer", "feet", "forge", "forged", "grog",
        "grip", "guard", "gut", "granite", "hand", "head", "heart", "helm", "hide", "hood", "horn",
        "jaw", "mace", "mail", "maker", "mantle", "mane", "master", "maul", "miner", "pike",
        "rock", "river", "shield", "shaper", "sword", "shoulder", "stone", "spine", "sunder",
        "thane", "toe", "tank", "view",
    ];

    let rnd7 = rand_max(NAME7.len());
    let rnd8 = rand_max(NAME8.len());

    match gender {
        NickGender::Female => {
            let rnd4 = rand_max(NAME4.len());
            let rnd5 = rand_max(NAME5.len());
            let rnd6 = rand_max(NAME6.len());

            String::from(NAME4[rnd4]) + NAME5[rnd5] + NAME6[rnd6] + " " + NAME7[rnd7] + NAME8[rnd8]
        }
        NickGender::Male => {
            let rnd1 = rand_max(NAME1.len());
            let rnd2 = rand_max(NAME2.len());
            let rnd3 = rand_max(NAME3.len());

            String::from(NAME1[rnd1]) + NAME2[rnd2] + NAME3[rnd3] + " " + NAME7[rnd7] + NAME8[rnd8]
        }
    }
}

pub fn barbarian(gender: NickGender) -> String {
    static NAME1: [&str; 18] = [
        "ae", "au", "ei", "a", "e", "i", "o", "u", "a", "e", "i", "o", "u", "a", "e", "i", "o", "u",
    ];
    static NAME2: [&str; 43] = [
        "", "", "", "b", "bl", "br", "bh", "d", "dr", "dh", "f", "fr", "g", "gh", "gr", "gl", "h",
        "hy", "hr", "j", "k", "kh", "kr", "l", "ll", "m", "n", "p", "pr", "r", "rh", "s", "sk",
        "sg", "sm", "sn", "st", "t", "th", "thr", "ty", "v", "y",
    ];
    static NAME3: [&str; 140] = [
        "bl", "br", "d", "db", "dbr", "dd", "ddg", "dg", "dl", "dm", "dr", "dv", "f", "fd", "fgr",
        "fk", "fl", "fn", "fr", "fst", "fv", "g", "gb", "gd", "gf", "gg", "ggv", "gl", "gn", "gr",
        "gss", "gv", "k", "kk", "l", "lb", "lc", "ld", "ldr", "lf", "lfr", "lg", "lgr", "lk", "ll",
        "llg", "llk", "llv", "lm", "ln", "lp", "lr", "ls", "lsk", "lsn", "lst", "lsv", "lt", "lv",
        "m", "md", "mk", "ml", "mm", "ms", "n", "nb", "nd", "ndr", "ng", "nl", "nn", "nng", "nr",
        "nsk", "nt", "nv", "nw", "p", "pl", "pp", "pr", "r", "rb", "rd", "rdg", "rf", "rg", "rgr",
        "rk", "rkm", "rl", "rls", "rm", "rn", "rng", "rngr", "rnh", "rnk", "rns", "rnv", "rr",
        "rst", "rt", "rth", "rtm", "rv", "s", "sb", "sbr", "sg", "sgr", "sk", "sl", "sm", "sn",
        "sr", "ssk", "st", "stm", "str", "sv", "t", "tg", "th", "thg", "thn", "thr", "thv", "tm",
        "tr", "tt", "ttf", "tv", "v", "yv", "z", "zg", "zl", "zn",
    ];
    static NAME4: [&str; 24] = [
        "d", "dr", "f", "g", "kr", "k", "l", "ld", "lf", "lk", "ll", "lr", "m", "mm", "n", "nd",
        "nn", "r", "rd", "rn", "rr", "s", "th", "t",
    ];
    static NAME5: [&str; 34] = [
        "", "", "", "b", "br", "bh", "ch", "d", "dh", "f", "fr", "g", "gh", "gr", "gw", "gl", "h",
        "j", "k", "kh", "m", "n", "r", "rh", "s", "sh", "st", "sv", "t", "th", "thr", "tr", "v",
        "w",
    ];
    static NAME6: [&str; 30] = [
        "ae", "ea", "ie", "ei", "io", "a", "e", "i", "o", "u", "a", "e", "i", "o", "u", "a", "e",
        "i", "o", "u", "a", "e", "i", "o", "u", "a", "e", "i", "o", "u",
    ];
    static NAME7: [&str; 91] = [
        "bj", "c", "d", "dd", "df", "dl", "dr", "f", "ff", "fl", "fn", "fr", "fth", "g", "gd",
        "gm", "gn", "gnh", "gr", "h", "hh", "k", "l", "ld", "lf", "lfh", "lg", "lgr", "lh", "lk",
        "ll", "lm", "lr", "ls", "lv", "m", "mm", "n", "nd", "ndr", "ng", "ngr", "ngv", "nh", "nl",
        "nn", "nnh", "nr", "ns", "nt", "nv", "r", "rd", "rf", "rg", "rgh", "rgr", "rh", "rk", "rl",
        "rm", "rn", "rnd", "rng", "rr", "rst", "rt", "rth", "rtr", "rv", "s", "sb", "sd", "sg",
        "sh", "sl", "st", "stn", "str", "sv", "t", "thr", "tk", "tr", "tt", "tth", "v", "y", "yj",
        "ym", "yn",
    ];
    static NAME8: [&str; 14] = [
        "", "", "", "", "f", "g", "h", "l", "n", "nn", "s", "sh", "th", "y",
    ];

    let rnd0 = rand_max(10);

    match gender {
        NickGender::Female => {
            let rnd5 = rand_max(NAME5.len());
            let rnd6 = rand_max(NAME6.len());
            let rnd8 = rand_max(NAME8.len());
            if rnd0 < 3 {
                let rnd5 = rnd5.max(5);

                make_ascii_title_case(String::from(NAME5[rnd5]) + NAME6[rnd6] + NAME8[rnd8])
            } else if rnd0 < 8 {
                let rnd62 = rand_max(NAME6.len()).max(5);
                let rnd7 = rand_max(NAME7.len());

                make_ascii_title_case(
                    String::from(NAME5[rnd5])
                        + NAME6[rnd6]
                        + NAME7[rnd7]
                        + NAME6[rnd62]
                        + NAME8[rnd8],
                )
            } else {
                let rnd62 = if rnd6 < 5 {
                    rand_max(NAME6.len()).max(5)
                } else {
                    rand_max(NAME6.len())
                };
                let rnd7 = rand_max(NAME7.len());
                let rnd72 = rand_max(NAME7.len());
                let rnd63 = rand_max(NAME6.len());

                make_ascii_title_case(
                    String::from(NAME5[rnd5])
                        + NAME6[rnd6]
                        + NAME7[rnd7]
                        + NAME6[rnd62]
                        + NAME7[rnd72]
                        + NAME6[rnd63],
                )
            }
        }
        NickGender::Male => {
            let rnd1 = rand_max(NAME1.len());
            let rnd2 = rand_max(NAME2.len());
            let rnd4 = rand_max(NAME4.len());

            if rnd0 < 3 {
                make_ascii_title_case(String::from(NAME2[rnd2]) + NAME1[rnd1] + NAME4[rnd4])
            } else if rnd0 < 8 {
                let rnd1b = if rnd2 < 3 {
                    rand_max(NAME1.len()).max(3)
                } else {
                    rand_max(NAME1.len())
                };
                let rnd3 = rand_max(NAME3.len());

                make_ascii_title_case(
                    String::from(NAME2[rnd2])
                        + NAME1[rnd1]
                        + NAME3[rnd3]
                        + NAME1[rnd1b]
                        + NAME4[rnd4],
                )
            } else {
                let rnd1b = if rnd2 < 3 {
                    rand_max(NAME1.len()).max(3)
                } else {
                    rand_max(NAME1.len())
                };
                let rnd3 = rand_max(NAME3.len());
                let rnd1c = rand_max(NAME1.len());
                let rnd3b = rand_max(NAME3.len());

                make_ascii_title_case(
                    String::from(NAME2[rnd2])
                        + NAME1[rnd1]
                        + NAME3[rnd3]
                        + NAME1[rnd1b]
                        + NAME3[rnd3b]
                        + NAME1[rnd1c]
                        + NAME4[rnd4],
                )
            }
        }
    }
}

pub fn elf(gender: NickGender) -> String {
    static NAME1: [&str; 561] = [
        "Mnementh",
        "Wirenth",
        "Feyrith",
        "Sataleeti",
        "Leofrick",
        "Abarat",
        "Adamar",
        "Adorellan",
        "Adresin",
        "Aelrindel",
        "Aerendyl",
        "Aeson",
        "Afamrail",
        "Agandaur",
        "Agis",
        "Aias",
        "Aiduin",
        "Aien",
        "Ailas",
        "Ailduin",
        "Ailen",
        "Ailluin",
        "Ailmar",
        "Ailmer",
        "Ailmon",
        "Ailre",
        "Ailred",
        "Ailuin",
        "Ailwin",
        "Aimar",
        "Aimer",
        "Aimon",
        "Airdan",
        "Aire",
        "Aired",
        "Aithlin",
        "Aiwin",
        "Akkar",
        "Alabyran",
        "Alaion",
        "Alas",
        "Albondiel",
        "Alduin",
        "Alen",
        "Alinar",
        "Alluin",
        "Almar",
        "Almer",
        "Almon",
        "Alok",
        "Alosrin",
        "Alre",
        "Alred",
        "Althidon",
        "Alwin",
        "Amrynn",
        "Andrathath",
        "Anfalen",
        "Anlyth",
        "Aolis",
        "Aquilan",
        "Arathorn",
        "Arbane",
        "Arbelladon",
        "Ardreth",
        "Ardryll",
        "Arl",
        "Arlen",
        "Arun",
        "Ascal",
        "Athtar",
        "Aubron",
        "Aumanas",
        "Aumrauth",
        "Avourel",
        "Ayas",
        "Ayduin",
        "Ayen",
        "Ayluin",
        "Aymar",
        "Aymer",
        "Aymon",
        "Ayre",
        "Ayred",
        "Aywin",
        "Belanor",
        "Beldroth",
        "Bellas",
        "Beluar",
        "Biafyndar",
        "Bialaer",
        "Braern",
        "Cailu",
        "Cameron",
        "Camus",
        "Castien",
        "Chathanglas",
        "Cheyrth",
        "Cluhurach",
        "Cluym",
        "Cohnal",
        "Conall",
        "Connak",
        "Cornaith",
        "Corym",
        "Cyran",
        "Dain",
        "Dakath",
        "Dalyor",
        "Darcassan",
        "Darfin",
        "Darthoridan",
        "Darunia",
        "Deldrach",
        "Delmuth",
        "Delsaran",
        "Devdan",
        "Drannor",
        "Druindar",
        "Durlan",
        "Durothil",
        "Dyffros",
        "Edwyrd",
        "Edyrm",
        "Ehlark",
        "Ehrendil",
        "Eilauver",
        "Elnaril",
        "Elaith",
        "Elandorr",
        "Elas",
        "Elashor",
        "Elbauthin",
        "Eldaernth",
        "Eldar",
        "Eldrin",
        "Elduin",
        "Elen",
        "Elephon",
        "Elidyr",
        "Elion",
        "Elkhazel",
        "Ellisar",
        "Elluin",
        "Elmar",
        "Elmer",
        "Elmon",
        "Elorshin",
        "Elpaerae",
        "Elre",
        "Elred",
        "Eltaor",
        "Elwin",
        "Elyon",
        "Emmyth",
        "Entrydal",
        "Erendriel",
        "Erglareo",
        "Eriladar",
        "Erlan",
        "Erlathan",
        "Eroan",
        "Erolith",
        "Eschallus",
        "Estelar",
        "Ethlando",
        "Ettrian",
        "Evindal",
        "Eyrynnhv",
        "Faelar",
        "Faelyn",
        "Faeranduil",
        "Falael",
        "Felaern",
        "Fenian",
        "Feno",
        "Fhaornik",
        "Filarion",
        "Filvendor",
        "Filverel",
        "Flardryn",
        "Flinar",
        "Folas",
        "Folduin",
        "Folen",
        "Folluin",
        "Folmar",
        "Folmer",
        "Folmon",
        "Folre",
        "Folred",
        "Folwin",
        "Foxfire",
        "Fylson",
        "Gaeleath",
        "Gaelin",
        "Galaeron",
        "Galan",
        "Galather",
        "Ganamede",
        "Gantar",
        "Garrik",
        "Garynnon",
        "Giullio",
        "Glanduil",
        "Glarald",
        "Glorandal",
        "Goll",
        "Goras",
        "Gorduin",
        "Goren",
        "Gorluin",
        "Gormar",
        "Gormer",
        "Gormon",
        "Gorre",
        "Gorred",
        "Gorwin",
        "Grathgor",
        "Haemir",
        "Hagas",
        "Hagduin",
        "Hagen",
        "Hagluin",
        "Hagmar",
        "Hagmer",
        "Hagre",
        "Hagred",
        "Hagwin",
        "Haladavar",
        "Halafarin",
        "Halamar",
        "Haldir",
        "Haldreithen",
        "Halflar",
        "Halueth",
        "Halueve",
        "Hamon",
        "Haryk",
        "Hastos",
        "Hatharal",
        "Hoccar",
        "Horith",
        "Hubyr",
        "Iefyr",
        "Ievos",
        "Ilbryn",
        "Ilimitar",
        "Iliphar",
        "Illianaro",
        "Illithor",
        "Illitran",
        "Ilphas",
        "Ilrune",
        "Ilthuryn",
        "Inchel",
        "Inialos",
        "Injros",
        "Intevar",
        "Iolas",
        "Iolrath",
        "Itham",
        "Ivsaar",
        "Ivlisar",
        "Ivran",
        "Iymbryl",
        "Iyrandrar",
        "Jandar",
        "Jannalor",
        "Jaonos",
        "Jassin",
        "Jhaan",
        "Jhaartael",
        "Jhaeros",
        "Jharak",
        "Jharym",
        "Jonik",
        "Jorildyn",
        "Josidiah",
        "Juppar",
        "Kailu",
        "Katar",
        "Katyr",
        "Keletheryl",
        "Kellam",
        "Kelvhan",
        "Kendel",
        "Kerym",
        "Keryth",
        "Kesefehon",
        "Kharis",
        "Khatar",
        "Khidell",
        "Khiiral",
        "Khilseith",
        "Khuumal",
        "Khyrmn",
        "Kieran",
        "Kiirion",
        "Kindroth",
        "Kivessin",
        "Kiyuigh",
        "Klaern",
        "Kolvar",
        "Kuornos",
        "Kuskyn",
        "Kymil",
        "Kyrenic",
        "Kyrtaar",
        "Laeroth",
        "Lafarallin",
        "Lamruil",
        "Laosx",
        "Larongar",
        "Larrel",
        "Lashul",
        "Lathai",
        "Lathlaeril",
        "Leojym",
        "Lhoris",
        "Lianthorn",
        "Llarm",
        "Llewellenar",
        "Llombaerth",
        "Lorsan",
        "Luirlan",
        "Luthais",
        "Luvon",
        "Lyari",
        "Lyklor",
        "Lysanthir",
        "Maeraddyth",
        "Maeral",
        "Maiele",
        "Malgath",
        "Malon",
        "Mardeiym",
        "Marikoth",
        "Marlevaur",
        "Melandrach",
        "Merellien",
        "Merith",
        "Methild",
        "Mhaenal",
        "Mi'tilarro",
        "Mihangyl",
        "Miirphys",
        "Mirthal",
        "Mlartlar",
        "Molonym",
        "Molostroi",
        "Montagor",
        "Morgan",
        "Morthil",
        "Myrddin",
        "Myriil",
        "Myrin",
        "Mythanthar",
        "Naertho",
        "Naeryndam",
        "Naesala",
        "Narbeth",
        "Nardual",
        "Nasir",
        "Navarre",
        "Nelaeryn",
        "Neldor",
        "Nesterin",
        "Nevarth",
        "Nhamashal",
        "Nieven",
        "Nindrol",
        "Ninleyn",
        "Ninthalor",
        "Nlossae",
        "Nopos",
        "Nremyn",
        "Nuvian",
        "Nylian",
        "Nym",
        "Nyvorlas",
        "Oacenth",
        "Oenel",
        "Ohmbryn",
        "Olaurae",
        "Onas",
        "Oncith",
        "Onvyr",
        "Orist",
        "Orlpar",
        "Orndacil",
        "Ornthalas",
        "Orrian",
        "Orym",
        "Oslarelar",
        "Otaehryn",
        "Othorion",
        "Paeral",
        "Paeris",
        "Pelleas",
        "Phaendar",
        "Pharom",
        "Phraan",
        "Pirphal",
        "Pleufan",
        "Purtham",
        "Pyrder",
        "Pyrravym",
        "Pywaln",
        "Qildor",
        "Quynn",
        "Raeranthur",
        "Raibyr",
        "Ralikanthae",
        "Ralnor",
        "Rathal",
        "Raunaeril",
        "Rauvelore",
        "Reluraun",
        "Reluvethel",
        "Rennyn",
        "Reptar",
        "Respen",
        "Rhaac'var",
        "Rhalyf",
        "Rhangyl",
        "Rhistel",
        "Rhothomir",
        "Rhys",
        "Rilitar",
        "Riluaneth",
        "Rolim",
        "Rothilion",
        "Ruardh",
        "Ruehar",
        "Ruith",
        "Ruvaen",
        "Ruven",
        "Ruvyn",
        "Rychell",
        "Rydel",
        "Ryfon",
        "Ryo",
        "Ryul",
        "Saelethil",
        "Saevel",
        "Saleh",
        "Samblar",
        "Sandevv",
        "Seiveril",
        "Selanlar",
        "Selgauth",
        "Sharian",
        "Shaundyl",
        "Shihon",
        "Shyrrik",
        "Siirist",
        "Silvyr",
        "Simimar",
        "Sinaht",
        "Skalanis",
        "Sontar",
        "Sorfildor",
        "Sudryl",
        "Sundamar",
        "Sylvar",
        "Symkalr",
        "Sythaeryn",
        "Taanyth",
        "Taegen",
        "Taenaran",
        "Taeral",
        "Taerntym",
        "Taleisin",
        "Tamnaeuth",
        "Tanithil",
        "Tannivh",
        "Tannyll",
        "Tanyl",
        "Taranath",
        "Tarathiel",
        "Taredd",
        "Tarron",
        "Tasar",
        "Tassarion",
        "Tathaln",
        "Tehlmar",
        "Teirist",
        "Thalanil",
        "Thallan",
        "Theodas",
        "Theodemar",
        "Theoden",
        "Theodluin",
        "Theodmer",
        "Theodmon",
        "Theodre",
        "Theodred",
        "Theoduin",
        "Theodwin",
        "Thurdan",
        "Tiarshus",
        "Tinlef",
        "Tlannatar",
        "Tolthe",
        "Tordynnar",
        "Toross",
        "Traeliorn",
        "Travaran",
        "Triandal",
        "Ualair",
        "Uevareth",
        "Uldreiyn",
        "Urddusk",
        "Usunaar",
        "Uthorim",
        "Vaalyun",
        "Vaeril",
        "Vamir",
        "Vander",
        "Vartan",
        "Velethuil",
        "Venali",
        "Vesperr",
        "Vesryn",
        "Vesstan",
        "Virion",
        "Volodar",
        "Voron",
        "Vuduin",
        "Vulas",
        "Vulen",
        "Vulluin",
        "Vulmar",
        "Vulmer",
        "Vulmon",
        "Vulre",
        "Vulred",
        "Vulwin",
        "Wistari",
        "Wylchyr",
        "Wyn",
        "Wyninn",
        "Wyrran",
        "Xalph",
        "Xanotter",
        "Xhalh",
        "Xhalth",
        "Xharlion",
        "Yalathanil",
        "Yeschant",
        "Yhendorn",
        "Ylyndar",
        "Zabbas",
        "Zaltarish",
        "Zandro",
        "Zaor",
        "Zaos",
        "Zelphar",
        "Zeno",
        "Zhoron",
    ];
    static NAME2: [&str; 372] = [
        "Sataleeti",
        "Leena",
        "Lithoniel",
        "Vanya",
        "Alasse",
        "Zentha",
        "Myantha",
        "Eloimaya",
        "Faraine",
        "Kylantha",
        "Celaena",
        "Aenwyn",
        "Maescia",
        "Tyrael",
        "Shearah",
        "Elisven",
        "Llorva",
        "Nimue",
        "Zaleria",
        "Aelrue",
        "Aelynthi",
        "Aerilaya",
        "Aerith",
        "Ahrendue",
        "Ahskahala",
        "Aila",
        "Alaglossa",
        "Alais",
        "Alanis",
        "Alavara",
        "Alea",
        "Aleesia",
        "Alenia",
        "Alerathla",
        "Allannia",
        "Allisa",
        "Alloralla",
        "Allynna",
        "Almedha",
        "Almithara",
        "Alvaerele",
        "Alyndra",
        "Amara",
        "Amaranthae",
        "Amedee",
        "Ameria",
        "Amkissra",
        "Amlaruil",
        "Amnestria",
        "Amra",
        "Anarzee",
        "Aneirin",
        "Anhaern",
        "Annallee",
        "Ara",
        "Araushnee",
        "Aravae",
        "Arcaena",
        "Ariawyn",
        "Arielimnda",
        "Arlayna",
        "Arnarra",
        "Arryn",
        "Arthion",
        "Artin",
        "Ashera",
        "Ashryn",
        "Auluua",
        "Aurae",
        "Ava",
        "Axilya",
        "Ayda",
        "Ayla",
        "Azariah",
        "Bellaluna",
        "Bemere",
        "Blythswana",
        "Bonnalurie",
        "Braerindra",
        "Burolia",
        "Caeda",
        "Caerthynna",
        "Calarel",
        "Cellica",
        "Chaenath",
        "Chalia",
        "Chalsarda",
        "Chandrelle",
        "Chasianna",
        "Chomylla",
        "Cilivren",
        "Ciyradyl",
        "Claire",
        "Cremia",
        "Cyithrel",
        "Daratrine",
        "Darshee",
        "Darunia",
        "Dasyra",
        "Dathlue",
        "Delimbiyra",
        "Delshandra",
        "Dessous",
        "Deularla",
        "Duilya",
        "Duru",
        "Eallyrl",
        "Ecaeris",
        "Edea",
        "Edraele",
        "Eirika",
        "Elanalue",
        "Elanil",
        "Elasha",
        "Elenaril",
        "Eletha",
        "Elincia",
        "Ellarian",
        "Elmyra",
        "Eloen",
        "Elora",
        "Elyon",
        "Ena",
        "Enania",
        "Eshenesra",
        "Essaerae",
        "Esta",
        "Esyae",
        "Falenas",
        "Farryn",
        "Faunalyn",
        "Fayeth",
        "Faylen",
        "Fhaertala",
        "Fi",
        "Fieryat",
        "Filaurel",
        "Filauria",
        "Fildaerae",
        "Gaelira",
        "Gaerradh",
        "Gaylia",
        "Gemstarzah",
        "Ghilanna",
        "Glynnii",
        "Gweyr",
        "Gwynnestri",
        "Gylledha",
        "Hacathra",
        "Haera",
        "Halaema",
        "Halanaestra",
        "Hamalitia",
        "Haramara",
        "Helartha",
        "Holone",
        "Huquethae",
        "Hycis",
        "Ialantha",
        "Ikeshia",
        "Ildilyntra",
        "Ilmadia",
        "Ilsevel",
        "Ilyana",
        "Ilyrana",
        "Ilythyrra",
        "Imizael",
        "Immianthe",
        "Imra",
        "Imryll",
        "Ioelena",
        "Irhaal",
        "Isilfarrel",
        "Isilynor",
        "Itiireae",
        "Itylra",
        "Iythronel",
        "Jastra",
        "Jeardra",
        "Jhanandra",
        "Jhaumrithe",
        "Jhiilsraa",
        "Kali",
        "Kasula",
        "Kavrala",
        "Kaylessa",
        "Kaylin",
        "Keenor",
        "Keerla",
        "Keishara",
        "Kenia ",
        "Kethryllia",
        "Keya",
        "Kilyn",
        "Kythaela",
        "Laamtora",
        "Laerdya",
        "Lazziar",
        "Leilatha",
        "Lenna",
        "Lensa",
        "Lethhonel",
        "Lierin",
        "Liluth",
        "Lixiss",
        "Llamryl",
        "Lorelei",
        "Lura",
        "Lusha",
        "Lusherina",
        "Lyeecia",
        "Lyeyeru",
        "Lyithion",
        "Lymsleia",
        "Lyndis",
        "Lyra",
        "Lyre",
        "Maelyrra",
        "Maeralya",
        "Makaela",
        "Malon",
        "Malruthiia",
        "Mariona",
        "Martainn",
        "Maylin",
        "Meira",
        "Melarue",
        "Merethyl",
        "Merialeth",
        "Meriel",
        "Merlara",
        "Micaiah",
        "Mladris",
        "Mnuvae",
        "Morgwais",
        "Moryggan",
        "Muerlara",
        "Mylaela",
        "Mylaerla",
        "Myriani",
        "Myrrh",
        "Nabooru",
        "Naesala",
        "Naevys",
        "Nakiasha",
        "Nambra",
        "Nanthleene",
        "Naumys",
        "Nei",
        "Nephenee",
        "Nexxis",
        "Nimronyn",
        "Nithenoel",
        "Nithroel",
        "Nlaea",
        "Nuala",
        "Nueleth",
        "Nuovis",
        "Nushala",
        "Nylaathria",
        "Nyna",
        "Ochyllyss",
        "Omylia",
        "Osonia",
        "Penelo",
        "Phaerl",
        "Phelorna",
        "Phuingara",
        "Phyrra",
        "Pyria",
        "Quamara",
        "Radelia",
        "Raejiisa",
        "Raerauntha",
        "Rania",
        "Ratha",
        "Rathiain",
        "Renestrae",
        "Renna",
        "Rina",
        "Riniya",
        "Rosaria",
        "Rosario",
        "Roshi",
        "Roshia",
        "Rubrae",
        "Ryllae",
        "Salihn",
        "Saelihn",
        "Saida",
        "Sakaala",
        "Sana",
        "Saria",
        "Sariandi",
        "Sarya",
        "Seirye",
        "Seldanna",
        "Selphie",
        "Selussa",
        "Shadowmoon",
        "Shalana",
        "Shalendra",
        "Shalheira",
        "Shandalar",
        "Shanyrria",
        "Sharaera",
        "Sharia",
        "Sheedra",
        "Sheera",
        "Shialaevar",
        "Shyael",
        "Shyilia",
        "Shyonia",
        "Sinnafain",
        "Solana",
        "Soliania",
        "Soora",
        "Sorsasta",
        "Sphiel",
        "Sumia",
        "Susklahava",
        "Sylmae",
        "Symrustar",
        "Syndra",
        "Syviis",
        "Taenya",
        "Taionia",
        "Talanashta",
        "Talila",
        "Talindra",
        "Tanelia",
        "Tanulia",
        "Tarasynora",
        "Teharissa",
        "Teryani",
        "Tethys",
        "Thalia",
        "Thaola",
        "Thasitalia",
        "Thessalia",
        "Tiatha",
        "Tinesia",
        "Tiriara",
        "Tisharu",
        "Tsarra",
        "Uiathen",
        "Ulelesse",
        "Umrielyth",
        "Urmicca",
        "Uschymna",
        "Valindra",
        "Vashti",
        "Velatha",
        "Verrona",
        "Vestele",
        "Viansola",
        "Viessa",
        "Wynnter",
        "Yaereene",
        "Yalanilue",
        "Yathlanae",
        "Ygrainne",
        "Ynshael",
        "Yrlissa",
        "Yrneha",
        "Yrthraethra",
        "Ysmyrlda",
        "Yulmanda",
        "Yunalesca",
        "Zilyana",
        "Zoastria",
        "Vaeri",
    ];
    static NAME3: [&str; 94] = [
        "Ad", "Ae", "Ara", "Bal", "Bei", "Bi", "Bry", "Cai", "Car", "Chae", "Cra", "Da", "Dae",
        "Dor", "Eil", "El", "Ela", "En", "Er", "Fa", "Fae", "Far", "Fen", "Gen", "Gil", "Glyn",
        "Gre", "Hei", "Hele", "Her", "Hola", "Ian", "Iar", "Ili", "Ina", "Jo", "Kea", "Kel", "Key",
        "Kris", "Leo", "Lia", "Lora", "Lu", "Mag", "Mia", "Mira", "Mor", "Nae", "Neri", "Nor",
        "Ola", "Olo", "Oma", "Ori", "Pa", "Per", "Pet", "Phi", "Pres", "Qi", "Qin", "Qui", "Ralo",
        "Rava", "Rey", "Ro", "Sar", "Sha", "Syl", "The", "Tor", "Tra", "Tris", "Ula", "Ume", "Uri",
        "Va", "Val", "Ven", "Vir", "Waes", "Wran", "Wyn", "Wysa", "Xil", "Xyr", "Yel", "Yes",
        "Yin", "Ylla", "Zin", "Zum", "Zyl",
    ];
    static NAME4: [&str; 100] = [
        "balar", "banise", "bella", "beros", "can", "caryn", "ceran", "cyne", "dan", "di",
        "dithas", "dove", "faren", "fiel", "fina", "fir", "geiros", "gella", "golor", "gwyn",
        "hana", "harice", "hice", "horn", "jeon", "jor", "jyre", "kalyn", "kas", "kian", "krana",
        "lamin", "lana", "lar", "lee", "len", "leth", "lynn", "maer", "maris", "menor", "moira",
        "myar", "mys", "na", "nala", "nan", "neiros", "nelis", "norin", "peiros", "petor", "phine",
        "phyra", "qen", "qirelle", "quinal", "ra", "ralei", "ran", "rel", "ren", "ric", "rie",
        "rieth", "ris", "ro", "rona", "rora", "roris", "salor", "sandoral", "satra", "stina",
        "sys", "thana", "thyra", "toris", "tris", "tumal", "valur", "varis", "ven", "vyre",
        "warin", "wenys", "wraek", "wynn", "xalim", "xidor", "xina", "xisys", "yarus", "ydark",
        "ynore", "yra", "zana", "zeiros", "zorwyn", "zumin",
    ];
    let rnd3 = rand_max(NAME3.len());
    let rnd4 = rand_max(NAME4.len());

    match gender {
        NickGender::Female => {
            let rnd2 = rand_max(NAME2.len());
            String::from(NAME2[rnd2]) + " " + NAME3[rnd3] + NAME4[rnd4]
        }
        NickGender::Male => {
            let rnd1 = rand_max(NAME1.len());
            String::from(NAME1[rnd1]) + " " + NAME3[rnd3] + NAME4[rnd4]
        }
    }
}

pub fn bandit(gender: NickGender) -> String {
    static NAMES_MALE: [&str; 1313] = [
        "Aaron",
        "Abel",
        "Abraham",
        "Abram",
        "Ackerley",
        "Ackley",
        "Acton",
        "Adam",
        "Adan",
        "Addisen",
        "Addison",
        "Aden",
        "Adger",
        "Adison",
        "Adrian",
        "Adriel",
        "Adrien",
        "Agustin",
        "Aidan",
        "Aiden",
        "Aiken",
        "Ailen",
        "Alan",
        "Albert",
        "Alcot",
        "Alcott",
        "Alden",
        "Alder",
        "Aldred",
        "Aldren",
        "Aldrich",
        "Aldridge",
        "Aldrych",
        "Alec",
        "Alex",
        "Alexander",
        "Alexzander",
        "Alf",
        "Alfie",
        "Alfred",
        "Alfredo",
        "Alfric",
        "Alfrid",
        "Allan",
        "Allard",
        "Allen",
        "Allie",
        "Allston",
        "Alton",
        "Alvertos",
        "Alvin",
        "Alwyn",
        "Amsden",
        "Anderson",
        "Andre",
        "Andrew",
        "Andy",
        "Ansley",
        "Anthony",
        "Antony",
        "Arden",
        "Arledge",
        "Arley",
        "Arlo",
        "Armstrong",
        "Arnold",
        "Aron",
        "Arthur",
        "Arundel",
        "Ashley",
        "Ashton",
        "Athelstan",
        "August",
        "Augustus",
        "Austen",
        "Austin",
        "Austyn",
        "Averill",
        "Awarnach",
        "Axel",
        "Ayden",
        "Bailey",
        "Ballard",
        "Bancroft",
        "Barclay",
        "Barden",
        "Barklay",
        "Barkley",
        "Barks",
        "Barksdale",
        "Barnet",
        "Barnett",
        "Baron",
        "Barr",
        "Barret",
        "Barrett",
        "Barron",
        "Barry",
        "Beacher",
        "Beaman",
        "Beardsley",
        "Bede",
        "Beldon",
        "Ben",
        "Benjamin",
        "Bennett",
        "Benny",
        "Bentley",
        "Bergen",
        "Bergess",
        "Berkeley",
        "Berkley",
        "Bernard",
        "Bert",
        "Berton",
        "Berty",
        "Billy",
        "Birch",
        "Blade",
        "Blake",
        "Blaze",
        "Bo",
        "Bob",
        "Bobby",
        "Bolton",
        "Bond",
        "Booker",
        "Booth",
        "Boothe",
        "Bordan",
        "Borden",
        "Brad",
        "Braden",
        "Bradford",
        "Bradley",
        "Bradly",
        "Bradney",
        "Brady",
        "Braeden",
        "Braedon",
        "Braid",
        "Bran",
        "Brand",
        "Branden",
        "Brandon",
        "Branford",
        "Brant",
        "Braxton",
        "Bray",
        "Brayan",
        "Brayden",
        "Braydon",
        "Brayton",
        "Brendan",
        "Brenden",
        "Brendon",
        "Brennan",
        "Brennen",
        "Brent",
        "Brentan",
        "Bret",
        "Brett",
        "Brewster",
        "Brian",
        "Brigham",
        "Brinley",
        "Brock",
        "Brocton",
        "Brod",
        "Broderick",
        "Brodie",
        "Brody",
        "Bromley",
        "Bromwell",
        "Bromwood",
        "Bronson",
        "Bronwen",
        "Bronwyn",
        "Brook",
        "Brooks",
        "Bruce",
        "Bruno",
        "Bryan",
        "Bryant",
        "Bryce",
        "Brycen",
        "Bryson",
        "Buckley",
        "Bud",
        "Burg",
        "Burgess",
        "Burley",
        "Burne",
        "Burns",
        "Burt",
        "Burton",
        "Buster",
        "Byrne",
        "Byron",
        "Cade",
        "Caden",
        "Cadwell",
        "Cael",
        "Cal",
        "Calder",
        "Caldwell",
        "Cale",
        "Calhoun",
        "Calvert",
        "Calvin",
        "Cameron",
        "Camren",
        "Camron",
        "Carden",
        "Carl",
        "Carleton",
        "Carlisle",
        "Carlo",
        "Carlos",
        "Carlton",
        "Carlyle",
        "Carrington",
        "Carson",
        "Carter",
        "Carvell",
        "Carver",
        "Casey",
        "Cason",
        "Catcher",
        "Caulder",
        "Cayden",
        "Cedric",
        "Chad",
        "Chadwick",
        "Chance",
        "Chandler",
        "Channing",
        "Chapman",
        "Charles",
        "Charley",
        "Charlie",
        "Charlton",
        "Chase",
        "Chaz",
        "Chevy",
        "Chilton",
        "Chip",
        "Chris",
        "Chuck",
        "Claiborne",
        "Clarence",
        "Clark",
        "Clay",
        "Clayton",
        "Cleavon",
        "Cleve",
        "Cleveland",
        "Cliff",
        "Clifford",
        "Clifton",
        "Clint",
        "Clinton",
        "Clive",
        "Coby",
        "Cody",
        "Colbert",
        "Colborn",
        "Colby",
        "Cole",
        "Coleman",
        "Colin",
        "Collin",
        "Colt",
        "Colten",
        "Colter",
        "Colton",
        "Conner",
        "Connor",
        "Conor",
        "Conrad",
        "Cooper",
        "Copper",
        "Corey",
        "Corin",
        "Cory",
        "Courtland",
        "Craig",
        "Crawford",
        "Creighton",
        "Cristian",
        "Cromwell",
        "Cruz",
        "Cullen",
        "Currier",
        "Curtis",
        "Cynric",
        "Cyrus",
        "Dakota",
        "Dale",
        "Dallas",
        "Dallin",
        "Dalton",
        "Damian",
        "Damien",
        "Damion",
        "Damon",
        "Dane",
        "Daniel",
        "Danny",
        "Darnell",
        "Darrel",
        "Darrell",
        "Darren",
        "Darrin",
        "Darrion",
        "Darrius",
        "Darryl",
        "Darryll",
        "Darwin",
        "Darwyn",
        "Daryl",
        "Daryll",
        "Dashawn",
        "David",
        "Davin",
        "Davion",
        "Davis",
        "Dayton",
        "Dean",
        "Declan",
        "Dempster",
        "Dennis",
        "Denton",
        "Denver",
        "Derek",
        "Derick",
        "Derrick",
        "Derwood",
        "Desmond",
        "Desmund",
        "Deven",
        "Devin",
        "Devon",
        "Devyn",
        "Dexter",
        "Dicken",
        "Dickens",
        "Dickenson",
        "Dickinson",
        "Digby",
        "Dillan",
        "Dillon",
        "Dion",
        "Dix",
        "Dixie",
        "Dixon",
        "Dob",
        "Dobbs",
        "Domenic",
        "Dominic",
        "Dominick",
        "Dominik",
        "Dominique",
        "Don",
        "Donald",
        "Donavan",
        "Donny",
        "Donovan",
        "Dorian",
        "Dorset",
        "Dorsey",
        "Douglas",
        "Dover",
        "Doyle",
        "Doyt",
        "Drake",
        "Drew",
        "Dudley",
        "Dudly",
        "Duncan",
        "Dunstan",
        "Durwald",
        "Durward",
        "Durwin",
        "Durwood",
        "Dustin",
        "Dwayne",
        "Dwenn",
        "Dwennon",
        "Dwight",
        "Dwighte",
        "Dwite",
        "Dwyght",
        "Dwyghte",
        "Dwyte",
        "Dylan",
        "Dylon",
        "Earl",
        "Eaton",
        "Ed",
        "Eddie",
        "Eddy",
        "Edgar",
        "Edmund",
        "Edsel",
        "Eduard",
        "Eduardo",
        "Edvard",
        "Edward",
        "Edwardo",
        "Edwards",
        "Edwardson",
        "Edwin",
        "Egerton",
        "Elbridge",
        "Elden",
        "Elder",
        "Eldon",
        "Eldridge",
        "Elfred",
        "Elijah",
        "Elliot",
        "Elliott",
        "Elman",
        "Elmar",
        "Elmer",
        "Elmore",
        "Elroy",
        "Elten",
        "Elton",
        "Elvin",
        "Elvis",
        "Emersen",
        "Emerson",
        "Emmerson",
        "Emmett",
        "Emmyrson",
        "Emyrson",
        "Eric",
        "Erick",
        "Erik",
        "Ernest",
        "Erskine",
        "Escott",
        "Esmond",
        "Esmund",
        "Ethan",
        "Ethen",
        "Eugene",
        "Evan",
        "Everett",
        "Ewart",
        "Ewing",
        "Fairfax",
        "Fairleigh",
        "Fairley",
        "Farland",
        "Farley",
        "Farly",
        "Farrell",
        "Felix",
        "Fielding",
        "Fleming",
        "Floyd",
        "Forbes",
        "Ford",
        "Forrest",
        "Francis",
        "Frank",
        "Frankie",
        "Franklin",
        "Fred",
        "Freddie",
        "Freddy",
        "Frederick",
        "Fredrick",
        "Free",
        "Fuller",
        "Fulton",
        "Gabriel",
        "Gael",
        "Gannon",
        "Garett",
        "Garfield",
        "Garret",
        "Garrett",
        "Garrick",
        "Garrison",
        "Garryson",
        "Gary",
        "Garyson",
        "Gaven",
        "Gavin",
        "Gavyn",
        "Geoffrey",
        "George",
        "Gerald",
        "Gerard",
        "Gilbert",
        "Gilford",
        "Glen",
        "Glenn",
        "Goldman",
        "Gordon",
        "Gower",
        "Grady",
        "Graham",
        "Granger",
        "Grant",
        "Gray",
        "Grayson",
        "Gregory",
        "Greyson",
        "Griffin",
        "Gunner",
        "Hadden",
        "Hadley",
        "Hagley",
        "Halbert",
        "Haley",
        "Hall",
        "Hallam",
        "Halsey",
        "Halton",
        "Hamilton",
        "Hannibal",
        "Harden",
        "Hardy",
        "Harlan",
        "Harman",
        "Harmon",
        "Harold",
        "Harrison",
        "Harry",
        "Harv",
        "Harvey",
        "Hastings",
        "Hawk",
        "Hawthorne",
        "Hayden",
        "Hayes",
        "Haywood",
        "Hector",
        "Hedley",
        "Hendrick",
        "Henley",
        "Henry",
        "Herbert",
        "Hilton",
        "Holden",
        "Hollis",
        "Horton",
        "Houston",
        "Howard",
        "Hudson",
        "Huey",
        "Hugh",
        "Hugo",
        "Hulk",
        "Humphrey",
        "Hunt",
        "Hunter",
        "Huntley",
        "Hutton",
        "Hyatt",
        "Ian",
        "Irvin",
        "Irving",
        "Ivan",
        "Ives",
        "Jack",
        "Jackson",
        "Jacob",
        "Jacoby",
        "Jaden",
        "Jadon",
        "Jadyn",
        "Jaeden",
        "Jagger",
        "Jaiden",
        "Jaime",
        "Jake",
        "Jakob",
        "James",
        "Jameson",
        "Jamie",
        "Jared",
        "Jarman",
        "Jarod",
        "Jarred",
        "Jarrett",
        "Jarrod",
        "Jarvis",
        "Jason",
        "Jasper",
        "Jaxon",
        "Jaxson",
        "Jay",
        "Jayson",
        "Jean",
        "Jeff",
        "Jeffery",
        "Jeffrey",
        "Jeremy",
        "Jerome",
        "Jerry",
        "Jesse",
        "Jessie",
        "Jett",
        "Jimmy",
        "Joe",
        "Joel",
        "Joey",
        "Johan",
        "John",
        "Johnny",
        "Jon",
        "Jonah",
        "Jonas",
        "Jordan",
        "Jorden",
        "Jordon",
        "Jordy",
        "Josef",
        "Joseph",
        "Josh",
        "Joshua",
        "Jude",
        "Julian",
        "Julien",
        "Junior",
        "Justin",
        "Justus",
        "Justyn",
        "Kameron",
        "Kamron",
        "Kane",
        "Karl",
        "Kasey",
        "Kayden",
        "Keanu",
        "Keaton",
        "Keegan",
        "Keenan",
        "Keith",
        "Kelvin",
        "Kenelm",
        "Kenley",
        "Kennedy",
        "Kenny",
        "Kent",
        "Kenton",
        "Keven",
        "Kevin",
        "Kevon",
        "Keyon",
        "Kim",
        "Kimberley",
        "King",
        "Kingsley",
        "Kinnard",
        "Kinnell",
        "Kinsey",
        "Kipp",
        "Kipper",
        "Kippy",
        "Kirk",
        "Knox",
        "Kobe",
        "Koby",
        "Kody",
        "Kole",
        "Korey",
        "Kory",
        "Kurt",
        "Kyle",
        "Lance",
        "Landan",
        "Landen",
        "Landon",
        "Lang",
        "Larry",
        "Lawrence",
        "Lawson",
        "Layton",
        "Lee",
        "Legolas",
        "Leigh",
        "Leland",
        "Leo",
        "Leon",
        "Leonard",
        "Leroy",
        "Lewis",
        "Liam",
        "Lincoln",
        "Lind",
        "Linden",
        "Linwood",
        "Litton",
        "Llewellyn",
        "Logan",
        "Louis",
        "Luc",
        "Lucas",
        "Lukas",
        "Luke",
        "Lyndon",
        "Lyre",
        "Lytton",
        "Mace",
        "Madison",
        "Maitland",
        "Malcolm",
        "Manley",
        "Manning",
        "Mansfield",
        "Manton",
        "Marc",
        "Marcel",
        "Marco",
        "Marcus",
        "Marden",
        "Mardyth",
        "Mark",
        "Markus",
        "Marland",
        "Marley",
        "Marlo",
        "Marlon",
        "Marlow",
        "Marlowe",
        "Marsden",
        "Marsdon",
        "Marshall",
        "Marston",
        "Martin",
        "Marvin",
        "Marwood",
        "Mather",
        "Mathew",
        "Matthew",
        "Maurice",
        "Maverick",
        "Max",
        "Maxim",
        "Maxwell",
        "Mead",
        "Melton",
        "Melville",
        "Melvin",
        "Michael",
        "Micheal",
        "Mike",
        "Miles",
        "Millard",
        "Miller",
        "Mills",
        "Millson",
        "Milt",
        "Milten",
        "Milton",
        "Milty",
        "Mitchel",
        "Morgan",
        "Morven",
        "Myles",
        "Nash",
        "Nathan",
        "Nathanael",
        "Nathanial",
        "Nathaniel",
        "Nathen",
        "Neal",
        "Nealson",
        "Ned",
        "Neddie",
        "Neddy",
        "Nedes",
        "Neil",
        "Neilson",
        "Nellie",
        "Nelly",
        "Nelson",
        "Neuman",
        "Neumann",
        "Newall",
        "Newbold",
        "Newell",
        "Newgate",
        "Newland",
        "Newlin",
        "Newman",
        "Newmie",
        "Newton",
        "Nicholas",
        "Nick",
        "Nickolas",
        "Nico",
        "Nicolas",
        "Nigel",
        "Nikolas",
        "Nilson",
        "Noah",
        "Noel",
        "Nolan",
        "Norm",
        "Normal",
        "Norman",
        "Normand",
        "Normie",
        "Norris",
        "North",
        "Norton",
        "Norville",
        "Norvin",
        "Norward",
        "Norwell",
        "Norwin",
        "Norwood",
        "Norwyn",
        "Nowles",
        "Numen",
        "Nyle",
        "Oakley",
        "Ogden",
        "Olin",
        "Oliver",
        "Orlando",
        "Orman",
        "Osbert",
        "Osborn",
        "Osborne",
        "Oscar",
        "Osmar",
        "Osmond",
        "Ossie",
        "Oswald",
        "Oswall",
        "Oswell",
        "Oswin",
        "Owen",
        "Oxford",
        "Oxon",
        "Oxton",
        "Ozzie",
        "Packard",
        "Palmer",
        "Park",
        "Parke",
        "Parker",
        "Parkley",
        "Parks",
        "Parr",
        "Parry",
        "Pat",
        "Paton",
        "Patrick",
        "Patten",
        "Pattin",
        "Patton",
        "Paul",
        "Paxton",
        "Payton",
        "Pearson",
        "Pelham",
        "Pell",
        "Pelton",
        "Penley",
        "Penn",
        "Perry",
        "Peter",
        "Peyton",
        "Philip",
        "Phillip",
        "Phoenix",
        "Pierce",
        "Pierson",
        "Prescott",
        "Presley",
        "Preston",
        "Priest",
        "Priestley",
        "Priestly",
        "Prince",
        "Putnam",
        "Putney",
        "Quinn",
        "Quinten",
        "Quintin",
        "Quinton",
        "Rab",
        "Rabbit",
        "Rad",
        "Radcliff",
        "Radcliffe",
        "Radclyf",
        "Radclyffe",
        "Radford",
        "Radley",
        "Radnor",
        "Rae",
        "Raff",
        "Raffi",
        "Raghnall",
        "Rai",
        "Raleigh",
        "Ralf",
        "Ralph",
        "Ralston",
        "Ramsay",
        "Ramsey",
        "Randy",
        "Ransden",
        "Ransford",
        "Ransley",
        "Ransom",
        "Raoul",
        "Raul",
        "Raven",
        "Ravi",
        "Ravinger",
        "Ravinia",
        "Rawley",
        "Rawlings",
        "Rawlins",
        "Rawls",
        "Rawly",
        "Rawson",
        "Ray",
        "Rayburn",
        "Rayfield",
        "Rayford",
        "Raymond",
        "Read",
        "Reade",
        "Reading",
        "Red",
        "Redd",
        "Redding",
        "Redfield",
        "Redford",
        "Redgrave",
        "Redman",
        "Redwald",
        "Reed",
        "Reg",
        "Reggie",
        "Reggy",
        "Reginald",
        "Regnauld",
        "Reid",
        "Reinald",
        "Reinhold",
        "Reinwald",
        "Rell",
        "Remington",
        "Remme",
        "Remmie",
        "Remmy",
        "Remy",
        "Renato",
        "Renault",
        "Rene",
        "Reuben",
        "Rey",
        "Reynold",
        "Reynolds",
        "Rhett",
        "Richard",
        "Rick",
        "Rider",
        "Ridley",
        "Rigby",
        "Riley",
        "Rinaldo",
        "Riobard",
        "Rip",
        "Ripley",
        "Rishley",
        "Riston",
        "Rob",
        "Robben",
        "Robbie",
        "Robbins",
        "Robby",
        "Rober",
        "Robert",
        "Roberto",
        "Robey",
        "Robin",
        "Robinson",
        "Rochester",
        "Rod",
        "Roddy",
        "Roderick",
        "Rodman",
        "Rodney",
        "Roger",
        "Rohan",
        "Roland",
        "Rolf",
        "Rolph",
        "Ronald",
        "Ronnie",
        "Ross",
        "Rowan",
        "Roy",
        "Ruben",
        "Rubert",
        "Ruddy",
        "Rudy",
        "Rudyard",
        "Rupert",
        "Russell",
        "Rutherford",
        "Ruthren",
        "Ryan",
        "Rycroft",
        "Ryder",
        "Rylan",
        "Ryland",
        "Ryle",
        "Rylee",
        "Ryley",
        "Ryman",
        "Rypley",
        "Ryton",
        "Sam",
        "Sammy",
        "Samson",
        "Sanborn",
        "Sandford",
        "Sandon",
        "Sandy",
        "Sanford",
        "Sawyer",
        "Scot",
        "Scott",
        "Scottie",
        "Scotty",
        "Seabert",
        "Seabright",
        "Seabrook",
        "Seabury",
        "Sean",
        "Seberg",
        "Sebert",
        "Seth",
        "Severn",
        "Seward",
        "Sewell",
        "Shane",
        "Shaun",
        "Shaw",
        "Shawn",
        "Shayne",
        "Sheldon",
        "Shell",
        "Shelley",
        "Shelli",
        "Shelly",
        "Shep",
        "Shepard",
        "Shepherd",
        "Shepley",
        "Sheppard",
        "Sherborne",
        "Sherlock",
        "Sherm",
        "Sherman",
        "Sherwin",
        "Sherwood",
        "Shipley",
        "Siddel",
        "Sidwell",
        "Simon",
        "Skylar",
        "Skyler",
        "Slade",
        "Snowden",
        "Snowdun",
        "Solomon",
        "Sonny",
        "Speck",
        "Spence",
        "Spencer",
        "Spenser",
        "Spike",
        "Stanberry",
        "Stanbury",
        "Stanfield",
        "Stanford",
        "Stanhope",
        "Stanleigh",
        "Stanley",
        "Stanly",
        "Stanmore",
        "Stanton",
        "Stanway",
        "Stanwick",
        "Stanwyck",
        "Stefan",
        "Stephan",
        "Stephen",
        "Stephon",
        "Steve",
        "Steven",
        "Stockman",
        "Stockton",
        "Stockwell",
        "Stokley",
        "Stroud",
        "Stuart",
        "Studs",
        "Sullivan",
        "Sydell",
        "Tanner",
        "Tate",
        "Taylor",
        "Ted",
        "Teddie",
        "Telford",
        "Terrance",
        "Terrel",
        "Terrell",
        "Terrence",
        "Terrill",
        "Terris",
        "Terry",
        "Thane",
        "Thatcher",
        "Theodore",
        "Thomas",
        "Thorald",
        "Thorbert",
        "Thorburn",
        "Thorley",
        "Thormond",
        "Thorn",
        "Thorndyke",
        "Thornton",
        "Thorne",
        "Thornley",
        "Thorpe",
        "Thurber",
        "Thurlow",
        "Thurman",
        "Thurmon",
        "Thurmond",
        "Timothy",
        "Tirell",
        "Tito",
        "Titus",
        "Tobias",
        "Toby",
        "Todd",
        "Tomas",
        "Tomkin",
        "Tomlin",
        "Tommy",
        "Tompkin",
        "Tony",
        "Torold",
        "Tostig",
        "Towne",
        "Townes",
        "Townley",
        "Townsend",
        "Trace",
        "Tranter",
        "Travis",
        "Travon",
        "Trent",
        "Trever",
        "Trevon",
        "Trevor",
        "Trey",
        "Tripp",
        "Tristan",
        "Tristen",
        "Tristin",
        "Triston",
        "True",
        "Trueman",
        "Truesdale",
        "Truman",
        "Trystan",
        "Tucker",
        "Turner",
        "Ty",
        "Tye",
        "Tyler",
        "Tyne",
        "Tyrell",
        "Vance",
        "Victor",
        "Vincent",
        "Wade",
        "Waggoner",
        "Wake",
        "Wakefield",
        "Wakeley",
        "Wakeman",
        "Walcot",
        "Walcott",
        "Walker",
        "Wallace",
        "Wallach",
        "Wallas",
        "Waller",
        "Wallie",
        "Wallis",
        "Wally",
        "Walsh",
        "Walter",
        "Walton",
        "Ward",
        "Wardell",
        "Warden",
        "Wardley",
        "Warfield",
        "Warford",
        "Warley",
        "Warmond",
        "Warren",
        "Warton",
        "Warwick",
        "Washington",
        "Watkins",
        "Watson",
        "Watt",
        "Waverly",
        "Way",
        "Wayland",
        "Waylon",
        "Wayne",
        "Webb",
        "Weber",
        "Webley",
        "Webster",
        "Welborne",
        "Welby",
        "Welch",
        "Weldon",
        "Welford",
        "Weller",
        "Welles",
        "Wells",
        "Welsh",
        "Welton",
        "Wes",
        "Wesley",
        "Wess",
        "Wessely",
        "West",
        "Westbrook",
        "Westby",
        "Westcott",
        "Westleigh",
        "Weston",
        "Wetherby",
        "Wheaton",
        "Wheeler",
        "Whit",
        "Whitby",
        "Whitcomb",
        "Whitelaw",
        "Whitfield",
        "Whitford",
        "Whitley",
        "Whitlock",
        "Whitman",
        "Whitmore,Whittaker",
        "Wiley",
        "Wilfred",
        "Wilfrid",
        "Wilfried",
        "Will",
        "William",
        "Willie",
        "Wilson",
        "Winchell",
        "Windham",
        "Windsor",
        "Winfield",
        "Winfred",
        "Winfrey",
        "Wingate",
        "Winslow",
        "Winston",
        "Winthrop",
        "Winton",
        "Winward",
        "Woodie",
        "Woodrow",
        "Woodruff",
        "Woodward",
        "Woody",
        "Wright",
        "Wylie",
        "Wyn",
        "Wyndam",
        "Wynton",
        "Xander",
        "Xavier",
        "Xzavier",
        "Zachary",
        "Zachery",
        "Zack",
        "Zackary",
        "Zackery",
        "Zavier",
    ];
    static NAMES_FEMALE: [&str; 964] = [
        "Arlissa",
        "Ariella",
        "Sybil",
        "Abagail",
        "Abbey",
        "Abbie",
        "Abbigail",
        "Abby",
        "Abigail",
        "Abigale",
        "Abigayle",
        "Addison",
        "Adeline",
        "Adriana",
        "Adrianna",
        "Adrienne",
        "Afton",
        "Agrona",
        "Aida",
        "Aileen",
        "Aimee",
        "Aislinn",
        "Alcott",
        "Alden",
        "Aldercy",
        "Alena",
        "Alex",
        "Alexa",
        "Alexia",
        "Alexis",
        "Alexus",
        "Alexys",
        "Alia",
        "Alice",
        "Alicia",
        "Alina",
        "Alisa",
        "Alisha",
        "Alison",
        "Alissa",
        "Aliya",
        "Aliyah",
        "Aliza",
        "Alize",
        "Allie",
        "Allison",
        "Ally",
        "Allyson",
        "Allyssa",
        "Alvina",
        "Alycia",
        "Alysa",
        "Alysha",
        "Alyson",
        "Alyssa",
        "Amanda",
        "Amber",
        "Amberjill",
        "Amelia",
        "Amy",
        "Ana",
        "Anabel",
        "Anastasia",
        "Andrea",
        "Angela",
        "Angelica",
        "Angelina",
        "Angeline",
        "Angelique",
        "Angie",
        "Anissa",
        "Anita",
        "Ann",
        "Anna",
        "Annabel",
        "Annabella",
        "Annabelle",
        "Anne",
        "Annette",
        "Annie",
        "Annika",
        "Ansley",
        "Antonia",
        "Arantxa",
        "Aria",
        "Ariana",
        "Arianna",
        "Ariel",
        "Arielle",
        "Arleigh",
        "Arlene",
        "Armani",
        "Aryanna",
        "Ash",
        "Ashby",
        "Ashe",
        "Ashford",
        "Ashi",
        "Ashlan",
        "Ashlee",
        "Ashleigh",
        "Ashley",
        "Ashli",
        "Ashlie",
        "Ashlin",
        "Ashling",
        "Ashly",
        "Ashlyn",
        "Ashlynn",
        "Aspen",
        "Astrid",
        "Athena",
        "Aubree",
        "Aubrey",
        "Aubrie",
        "Audery",
        "Audey",
        "Audie",
        "Audra",
        "Audrey",
        "Audry",
        "Aurora",
        "Autumn",
        "Ava",
        "Avery",
        "Avon",
        "Ayana",
        "Ayanna",
        "Ayla",
        "Aylin",
        "Bailee",
        "Bailey",
        "Barbara",
        "Baxter",
        "Baylee",
        "Belen",
        "Bella",
        "Berenice",
        "Bert",
        "Berta",
        "Berthe",
        "Bertie",
        "Bethany",
        "Bev",
        "Beverely",
        "Beverley",
        "Beverly",
        "Bianca",
        "Blaine",
        "Blanca",
        "Blossom",
        "Blythe",
        "Bobbi",
        "Bobbie",
        "Bobby",
        "Brandi",
        "Brandy",
        "Brea",
        "Breana",
        "Breanna",
        "Brenda",
        "Brenna",
        "Breonna",
        "Bria",
        "Briana",
        "Brianna",
        "Brianne",
        "Bridget",
        "Brielle",
        "Brionna",
        "Brisa",
        "Britney",
        "Brittany",
        "Brittney",
        "Brook",
        "Brooke",
        "Brookes",
        "Brooks",
        "Bryana",
        "Bryanna",
        "Buffy",
        "Cady",
        "Caitlin",
        "Caitlyn",
        "Cali",
        "Calista",
        "Callie",
        "Cam",
        "Cameron",
        "Camila",
        "Camille",
        "Camm",
        "Cammie",
        "Camyron",
        "Cara",
        "Carina",
        "Carissa",
        "Carla",
        "Carlee",
        "Carley",
        "Carli",
        "Carlie",
        "Carling",
        "Carly",
        "Carmen",
        "Carol",
        "Carolina",
        "Caroline",
        "Carolyn",
        "Carrie",
        "Carson",
        "Casandra",
        "Casey",
        "Cassandra",
        "Cassidy",
        "Cassie",
        "Catalina",
        "Catherine",
        "Cayla",
        "Cecelia",
        "Cecilia",
        "Celeste",
        "Celia",
        "Celina",
        "Celine",
        "Chana",
        "Charity",
        "Charlotte",
        "Chasity",
        "Chaya",
        "Chelsea",
        "Chelsey",
        "Chelsie",
        "Cheyanne",
        "Cheyenne",
        "Chloe",
        "Christa",
        "Christian",
        "Christiana",
        "Christina",
        "Christine",
        "Christy",
        "Cindy",
        "Claiborne",
        "Claire",
        "Clara",
        "Clare",
        "Clarissa",
        "Claudia",
        "Clothilde",
        "Clotilde",
        "Clovis",
        "Colleen",
        "Columbia",
        "Cora",
        "Corinne",
        "Corliss",
        "Courtney",
        "Cristal",
        "Cristina",
        "Crystal",
        "Cynthia",
        "Daisey",
        "Daisy",
        "Dakota",
        "Damie",
        "Dana",
        "Dania",
        "Daniela",
        "Daniella",
        "Danielle",
        "Danna",
        "Daphne",
        "Daralis",
        "Darlene",
        "Dasia",
        "Dawn",
        "Deborah",
        "Delilah",
        "Demelza",
        "Demie",
        "Denise",
        "Denisse",
        "Desirae",
        "Desiree",
        "Destinee",
        "Destiney",
        "Destini",
        "Destiny",
        "Devon",
        "Diana",
        "Diane",
        "Dianna",
        "Dominique",
        "Donna",
        "Dorothy",
        "Eartha",
        "Easter",
        "Ebony",
        "Eda",
        "Edda",
        "Eden",
        "Edith",
        "Edlyn",
        "Edolie",
        "Edsel",
        "Eileen",
        "Elaina",
        "Elaine",
        "Eleanor",
        "Elena",
        "Eliana",
        "Elisa",
        "Elisabeth",
        "Elise",
        "Elissa",
        "Eliza",
        "Elizabeth",
        "Ella",
        "Elle",
        "Ellen",
        "Ellie",
        "Elsa",
        "Elyse",
        "Elyssa",
        "Ember",
        "Emely",
        "Emerson",
        "Emilee",
        "Emilia",
        "Emilie",
        "Emily",
        "Emma",
        "Ena",
        "Enna",
        "Erica",
        "Ericka",
        "Erika",
        "Erin",
        "Esther",
        "Ethel",
        "Eva",
        "Eve",
        "Evelin",
        "Evelyn",
        "Faith",
        "Farrah",
        "Fearn",
        "Fearne",
        "Felicia",
        "Felicity",
        "Fern",
        "Ferne",
        "Fernly",
        "Fiona",
        "Fleta",
        "Gabriela",
        "Gabriella",
        "Gabrielle",
        "Gail",
        "Gale",
        "Gayle",
        "Genevieve",
        "Gia",
        "Giana",
        "Gianna",
        "Gillian",
        "Gina",
        "Gioa",
        "Giselle",
        "Gisselle",
        "Gleda",
        "Gloria",
        "Godiva",
        "Golda",
        "Goldie",
        "Grace",
        "Gracie",
        "Gretchen",
        "Gwendolyn",
        "Gypsy",
        "Gytha",
        "Hadley",
        "Hailee",
        "Hailey",
        "Hailie",
        "Haleigh",
        "Haley",
        "Halie",
        "Halle",
        "Hallie",
        "Halsey",
        "Hana",
        "Hanna",
        "Hannah",
        "Harley",
        "Harmony",
        "Harva",
        "Harvelle",
        "Harvina",
        "Harvine",
        "Hayden",
        "Haylee",
        "Hayleigh",
        "Hayley",
        "Haylie",
        "Hazel",
        "Heather",
        "Hedwig",
        "Heidi",
        "Helen",
        "Helena",
        "Hertha",
        "Hollace",
        "Hollee",
        "Holli",
        "Hollie",
        "Holly",
        "Hollye",
        "Honey",
        "Hope",
        "Ida",
        "Idina",
        "Iliana",
        "Ingrid",
        "Irene",
        "Iris",
        "Isabel",
        "Isabela",
        "Isabell",
        "Isabella",
        "Isabelle",
        "Isolda",
        "Ivy",
        "Izabella",
        "Jacey",
        "Jackeline",
        "Jaclyn",
        "Jacqueline",
        "Jacquelyn",
        "Jada",
        "Jade",
        "Jaden",
        "Jadyn",
        "Jaelyn",
        "Jaida",
        "Jaiden",
        "Jaidyn",
        "Jailyn",
        "Jaime",
        "Jamie",
        "Jana",
        "Janae",
        "Jane",
        "Janet",
        "Janice",
        "Janie",
        "Jaquelin",
        "Jaqueline",
        "Jasmin",
        "Jasmine",
        "Jasmyn",
        "Jayda",
        "Jayde",
        "Jayden",
        "Jayla",
        "Jaylene",
        "Jaylin",
        "Jaylyn",
        "Jaylynn",
        "Jazlyn",
        "Jazmin",
        "Jazmine",
        "Jazmyn",
        "Jazmyne",
        "Jeanette",
        "Jena",
        "Jenifer",
        "Jenna",
        "Jennifer",
        "Jenny",
        "Jessica",
        "Jessie",
        "Jill",
        "Jillian",
        "Joana",
        "Joanna",
        "Jocelyn",
        "Joelle",
        "Johana",
        "Johanna",
        "Joia",
        "Joie",
        "Jolie",
        "Jonesy",
        "Joselyn",
        "Josephine",
        "Josie",
        "Joslyn",
        "Journey",
        "Joy",
        "Joyce",
        "Judith",
        "Julia",
        "Juliana",
        "Julianna",
        "Julianne",
        "Julie",
        "Juliet",
        "Juliette",
        "Justine",
        "Kacie",
        "Kaela",
        "Kaelyn",
        "Kaila",
        "Kailee",
        "Kailey",
        "Kailyn",
        "Kaitlin",
        "Kaitlyn",
        "Kaitlynn",
        "Kaiya",
        "Kaleigh",
        "Kaley",
        "Kali",
        "Kaliyah",
        "Kallie",
        "Kalyn",
        "Kara",
        "Karen",
        "Kari",
        "Karla",
        "Karlee",
        "Karley",
        "Karli",
        "Karlie",
        "Karly",
        "Kasandra",
        "Kasey",
        "Kassandra",
        "Kassidy",
        "Katarina",
        "Kate",
        "Katelin",
        "Katelyn",
        "Katelynn",
        "Katerina",
        "Katharine",
        "Katherine",
        "Kathleen",
        "Kathryn",
        "Kathy",
        "Katie",
        "Katlyn",
        "Katrina",
        "Katy",
        "Kayla",
        "Kaylah",
        "Kaylee",
        "Kayleigh",
        "Kayley",
        "Kayli",
        "Kaylie",
        "Kaylin",
        "Kaylyn",
        "Kaylynn",
        "Keeley",
        "Keely",
        "Keila",
        "Keira",
        "Kelli",
        "Kellie",
        "Kelly",
        "Kelsey",
        "Kelsi",
        "Kelsie",
        "Kelsy",
        "Kemble",
        "Kendra",
        "Kenya",
        "Kenzie",
        "Keyla",
        "Kiana",
        "Kianna",
        "Kiara",
        "Kiera",
        "Kierra",
        "Kiersten",
        "Kiley",
        "Kim",
        "Kimball",
        "Kimbell",
        "Kimberley",
        "Kimberly",
        "Kimble",
        "Kimby",
        "Kimmey",
        "Kimmi",
        "Kimmie",
        "Kimmy",
        "Kira",
        "Kirsten",
        "Kiya",
        "Kourtney",
        "Krista",
        "Kristen",
        "Kristin",
        "Kristina",
        "Kya",
        "Kyla",
        "Kylee",
        "Kyleigh",
        "Kylie",
        "Kym",
        "Kymberly",
        "Kyra",
        "Lacey",
        "Laila",
        "Lana",
        "Laney",
        "Lara",
        "Larissa",
        "Laura",
        "Laurel",
        "Lauren",
        "Lauryn",
        "Layla",
        "Lea",
        "Leah",
        "Lee",
        "Leigh",
        "Leila",
        "Leslie",
        "Lexi",
        "Lexie",
        "Liana",
        "Libby",
        "Liberty",
        "Lila",
        "Lilian",
        "Liliana",
        "Lillian",
        "Lilliana",
        "Lillie",
        "Lilly",
        "Lily",
        "Lina",
        "Linda",
        "Lindsay",
        "Lindsey",
        "Lisa",
        "Lisbeth",
        "Lizbeth",
        "Lizeth",
        "Lizette",
        "Locke",
        "Loella",
        "Loren",
        "Lorena",
        "Louella",
        "Love",
        "Lovie",
        "Lucia",
        "Lucy",
        "Luella",
        "Luelle",
        "Lydia",
        "Lyndsey",
        "Lyric",
        "Macey",
        "Maci",
        "Macie",
        "Mackenzie",
        "Macy",
        "Madalyn",
        "Madalynn",
        "Maddison",
        "Madeleine",
        "Madeline",
        "Madelyn",
        "Madelynn",
        "Madilyn",
        "Madisen",
        "Madison",
        "Madisyn",
        "Mady",
        "Madyson",
        "Maegan",
        "Maeve",
        "Maggie",
        "Maia",
        "Maida",
        "Maidel",
        "Maidie",
        "Maidy",
        "Maisie",
        "Maitane",
        "Makaila",
        "Makayla",
        "Makenzie",
        "Mallory",
        "Manda",
        "Mandy",
        "Manhattan",
        "Manny",
        "Margaret",
        "Margarita",
        "Maria",
        "Mariah",
        "Mariam",
        "Mariana",
        "Marianna",
        "Maribel",
        "Marie",
        "Mariela",
        "Marilyn",
        "Marina",
        "Marisa",
        "Marissa",
        "Marlee",
        "Marlene",
        "Marley",
        "Martha",
        "Mary",
        "Maya",
        "Mayda",
        "Mckayla",
        "Mckenna",
        "Mckenzie",
        "Meadow",
        "Meagan",
        "Meaghan",
        "Megan",
        "Meghan",
        "Melanie",
        "Melany",
        "Melina",
        "Melinda",
        "Melissa",
        "Melody",
        "Meredith",
        "Mia",
        "Miah",
        "Michelle",
        "Mina",
        "Miracle",
        "Miranda",
        "Miriam",
        "Mirth",
        "Missie",
        "Missy",
        "Missye",
        "Mistee",
        "Mistey",
        "Misty",
        "Miya",
        "Mollie",
        "Molly",
        "Monica",
        "Monique",
        "Montana",
        "Morgan",
        "Mya",
        "Myah",
        "Myra",
        "Nadia",
        "Nancy",
        "Naomi",
        "Nara",
        "Natalia",
        "Natalie",
        "Nataly",
        "Natasha",
        "Nathalie",
        "Nia",
        "Nichole",
        "Nicole",
        "Nikki",
        "Nina",
        "Nora",
        "Nya",
        "Nyah",
        "Olivia",
        "Paige",
        "Palma",
        "Palmiera",
        "Palmira",
        "Palmyra",
        "Pamela",
        "Parker",
        "Patience",
        "Patricia",
        "Paula",
        "Paulina",
        "Penelope",
        "Phoebe",
        "Piper",
        "Poppy",
        "Priscila",
        "Priscilla",
        "Pyper",
        "Queena",
        "Rachel",
        "Radella",
        "Raven",
        "Reanna",
        "Rebeca",
        "Rebecca",
        "Rebekah",
        "Reese",
        "Regina",
        "Reilly",
        "Renee",
        "Reyna",
        "Riley",
        "Rita",
        "Riya",
        "Robbin",
        "Roberta",
        "Robin",
        "Robina",
        "Robinette",
        "Robyn",
        "Rosa",
        "Rose",
        "Rosemary",
        "Roxana",
        "Ruby",
        "Ruperta",
        "Ruth",
        "Rylee",
        "Ryleigh",
        "Rylie",
        "Sabrina",
        "Sage",
        "Saige",
        "Sally",
        "Samantha",
        "Samara",
        "Sandra",
        "Sandy",
        "Sara",
        "Sarah",
        "Sasha",
        "Scarlet",
        "Scarlett",
        "Selby",
        "Selden",
        "Seldon",
        "Selena",
        "Selina",
        "Selwin",
        "Selwyn",
        "Serena",
        "Serenity",
        "Shandy",
        "Shannon",
        "Sharon",
        "Sheila",
        "Sherey",
        "Sherlie",
        "Shir",
        "Shirl",
        "Shirlee",
        "Shirleen",
        "Shirleigh",
        "Shirley",
        "Shurl",
        "Shurlie",
        "Sidney",
        "Simone",
        "Sky",
        "Skye",
        "Skyla",
        "Skylar",
        "Skyler",
        "Sofia",
        "Sonia",
        "Sonya",
        "Sophia",
        "Sophie",
        "Stacey",
        "Stacy",
        "Stella",
        "Stephanie",
        "Stephany",
        "Storm",
        "Storme",
        "Stormie",
        "Stormy",
        "Summer",
        "Susan",
        "Susana",
        "Sydnee",
        "Sydney",
        "Sydni",
        "Sydnie",
        "Sylvia",
        "Tait",
        "Taite",
        "Taitum",
        "Talia",
        "Tamara",
        "Tamia",
        "Tania",
        "Taniya",
        "Tanya",
        "Tara",
        "Tat",
        "Tatiana",
        "Tatum",
        "Tatyana",
        "Tavia",
        "Taya",
        "Tayler",
        "Tayte",
        "Teresa",
        "Tess",
        "Tessa",
        "Thalia",
        "Theresa",
        "Thistle",
        "Tia",
        "Tiana",
        "Tianna",
        "Tiffany",
        "Tina",
        "Tori",
        "Tracy",
        "Trinity",
        "Trudy",
        "Tuesday",
        "Ulla",
        "Vala",
        "Valentina",
        "Valeria",
        "Valerie",
        "Vanesa",
        "Vanessa",
        "Veronica",
        "Victoria",
        "Violet",
        "Virginia",
        "Vivian",
        "Viviana",
        "Wendy",
        "Whitney",
        "Willow",
        "Wilona",
        "Winifred",
        "Winter",
        "Yasmin",
        "Yasmine",
        "Yazmin",
        "Yedda",
        "Yetta",
        "Yolanda",
        "Yuliana",
        "Yvette",
        "Yvonne",
        "Zaria",
        "Zoe",
        "Zoey",
        "Zoie",
    ];
    static NAME2: [&str; 115] = [
        "Angel Eyes",
        "Bandana",
        "Black Eye",
        "Black Eyes",
        "Blackjack",
        "Blue Eyes",
        "Bulletproof",
        "Bullettooth",
        "Bullseye",
        "Coins",
        "Crackers",
        "Crazy Eyes",
        "Danger",
        "Dangerous",
        "Diamond",
        "Eyepatch",
        "Fast Fingers",
        "Five Fingers",
        "Four Fingers",
        "Ghost",
        "Gold Digger",
        "Greed",
        "Grimm",
        "Grin",
        "Luck",
        "Mad Dog",
        "Mad Eye",
        "Mad Eyes",
        "Mad Man",
        "Moneybags",
        "Muscles",
        "Nightmare",
        "Nine Lives",
        "Numbers",
        "One Eye",
        "Phantom",
        "Poison",
        "Razor",
        "Scarface",
        "Scars",
        "Shades",
        "Smokes",
        "Straight Jacket",
        "Three Fingers",
        "Three Toes",
        "Toothless",
        "Two Face",
        "Whisper",
        "Whispers",
        "the Angel",
        "the Bandit",
        "the Beast",
        "the Brute",
        "the Bug",
        "the Bull",
        "the Buster",
        "the Cheat",
        "the Cheater",
        "the Clown",
        "the Con",
        "the Con Artist",
        "the Crackpot",
        "the Crazy",
        "the Crook",
        "the Danger",
        "the Diamond",
        "the Dwarf",
        "the Eccentric",
        "the Fang",
        "the Fool",
        "the Greedy",
        "the Grin",
        "the Heist",
        "the Heister",
        "the Jester",
        "the Knuckles",
        "the Lucky",
        "the Lunatic",
        "the Mad",
        "the Maniac",
        "the Menace",
        "the Mumbler",
        "the Nightmare",
        "the Outlaw",
        "the Pegleg",
        "the Phantom",
        "the Pickpocket",
        "the Pillager",
        "the Pirate",
        "the Professional",
        "the Punk",
        "the Rat",
        "the Ravager",
        "the Razor",
        "the Reaper",
        "the Robber",
        "the Rogue",
        "the Scar",
        "the Serpent",
        "the Shark",
        "the Silent",
        "the Sly",
        "the Smile",
        "the Smirk",
        "the Snake",
        "the Spider",
        "the Squint",
        "the Suit",
        "the Swindler",
        "the Thief",
        "the Thug",
        "the Viper",
        "the Weasel",
        "the Whisper",
        "the Wild",
    ];
    static NAME3: [&str; 85] = [
        "Action",
        "Angel Eyes",
        "Bandana",
        "Black Eyed",
        "Blackjack",
        "Blue Eyed",
        "Brute",
        "Bug Eyed",
        "Bulletproof",
        "Bullettooth",
        "Bullseye",
        "Busting",
        "Cheating",
        "Coughing",
        "Crackpot",
        "Crazy",
        "Crazy Eyed",
        "Crazy Eyes",
        "Dangerous",
        "Diamond",
        "Dingbat",
        "Eccentric",
        "Eyepatch",
        "Fast Fingers",
        "Five Fingered",
        "Foolish",
        "Four Fingered",
        "Fruitcake",
        "Gold Digger",
        "Greedy",
        "Grinning",
        "Jester",
        "Klepto",
        "Knuckles",
        "Luaghing",
        "Lucky",
        "Lunatic",
        "Mad",
        "Mad Dog",
        "Mad Eyed",
        "Mad Hat",
        "Mad Man",
        "Menacing",
        "Moneybags",
        "Mumbling",
        "Muscled",
        "Nightmare",
        "Nine Lives",
        "Numbers",
        "One Eye",
        "Pegleg",
        "Phantom",
        "Pickpocket",
        "Poison",
        "Prowling",
        "Razor",
        "Razortooth",
        "Reaper",
        "Robbing",
        "Rusty",
        "Scarface",
        "Scars",
        "Serpent",
        "Shades",
        "Shark",
        "Silent",
        "Slithering",
        "Sly",
        "Smiling",
        "Smirking",
        "Smokey",
        "Spider",
        "Squinting",
        "Straight Jacket",
        "Swindling",
        "Thieving",
        "Three Fingered",
        "Three Toed",
        "Toothless",
        "Two Face",
        "Viper",
        "Wacko",
        "Weasel",
        "Whispering",
        "Wild",
    ];

    match gender {
        NickGender::Female => {
            let rnd1 = rand_max(NAMES_FEMALE.len());
            let rnd2 = rand_max(NAME2.len());
            make_ascii_title_case(String::from(NAMES_FEMALE[rnd1]))
                + " "
                + &make_ascii_title_case(String::from(NAME2[rnd2]))
        }
        NickGender::Male => {
            let rnd1 = rand_max(NAMES_MALE.len());
            let rnd3 = rand_max(NAME3.len());
            make_ascii_title_case(String::from(NAMES_MALE[rnd1]))
                + " "
                + &make_ascii_title_case(String::from(NAME3[rnd3]))
        }
    }
}

pub fn demon() -> String {
    static NAME1: [&str; 160] = [
        "baal", "bal", "bael", "bar", "barb", "bas", "bat", "beal", "beb", "beel", "beh", "bel",
        "ber", "bil", "bin", "bit", "bof", "bol", "bot", "bun", "bul", "cam", "car", "caym", "cer",
        "char", "chax", "cher", "cim", "cor", "cul", "cur", "dan", "djin", "dar", "fam", "foc",
        "for", "fur", "far", "fhar", "fhur", "fhor", "fham", "gad", "gak", "gam", "gaem", "gob",
        "gom", "gin", "gor", "grem", "gus", "guz", "hab", "hal", "han", "hav", "haur", "hyg",
        "hir", "hum", "jik", "jin", "kas", "kim", "kok", "kos", "lab", "lam", "lem", "ler", "ler",
        "lek", "lil", "mal", "mam", "mar", "mas", "mat", "med", "mel", "mep", "mer", "mol", "mor",
        "mur", "nab", "nap", "neq", "nin", "pay", "paz", "per", "phen", "pin", "pir", "pit", "pul",
        "pur", "qen", "rab", "rah", "raim", "raum", "ron", "ron", "rum", "rum", "rus", "sab",
        "sal", "sam", "sear", "seir", "sem", "sep", "shax", "shed", "sid", "sip", "sit", "stol",
        "sur", "syd", "tan", "tap", "ten", "tham", "tip", "ton", "tum", "tur", "vad", "val", "van",
        "vap", "vas", "ve", "vep", "vep", "vin", "vol", "vos", "vual", "wal", "xez", "xer", "xar",
        "xaz", "xaer", "zag", "zaeb", "zep", "zim", "zar", "zam", "zaem", "xan",
    ];
    static NAME3: [&str; 454] = [
        "ba", "bae", "bai", "bao", "bau", "be", "bea", "bei", "beo", "beu", "bi", "bia", "bie",
        "bio", "biu", "bo", "boa", "boi", "bou", "bu", "bua", "bue", "bui", "buo", "ca", "cae",
        "cai", "cao", "cau", "ce", "cea", "cei", "ceo", "ceu", "ci", "cia", "cio", "ciu", "co",
        "coa", "coi", "cou", "cu", "cua", "cue", "cui", "cuo", "da", "dae", "dai", "dao", "dau",
        "de", "dea", "dei", "deo", "deu", "di", "dia", "dio", "diu", "do", "doa", "doi", "dou",
        "du", "dua", "due", "dui", "duo", "fa", "fae", "fai", "fao", "fau", "fe", "fea", "fei",
        "feo", "feu", "fi", "fia", "fie", "fio", "fiu", "fo", "foa", "foi", "fou", "fu", "fua",
        "fue", "fui", "fuo", "ga", "gae", "gai", "gao", "gau", "ge", "gea", "gei", "geo", "geu",
        "gi", "gia", "gie", "gio", "giu", "go", "goa", "goi", "gou", "gu", "gua", "gue", "gui",
        "guo", "ha", "hae", "hai", "hao", "hau", "he", "hea", "hei", "heo", "heu", "hi", "hia",
        "hie", "hio", "hiu", "ho", "hoa", "hoi", "hou", "hu", "hua", "hue", "hui", "huo", "ka",
        "kae", "kai", "kao", "kau", "ke", "kea", "kei", "keo", "keu", "ki", "kia", "kie", "kio",
        "kiu", "ko", "koa", "koi", "kou", "ku", "kua", "kue", "kui", "kuo", "la", "lae", "lai",
        "lao", "lau", "le", "lea", "lei", "leo", "leu", "li", "lia", "lie", "lio", "liu", "lo",
        "loa", "loi", "lou", "lu", "lua", "lue", "lui", "luo", "ma", "mae", "mai", "mao", "mau",
        "me", "mea", "mei", "meo", "meu", "mi", "mia", "mie", "mio", "miu", "mo", "moa", "moi",
        "mou", "mu", "mua", "mue", "mui", "muo", "na", "nae", "nai", "nao", "nau", "ne", "nea",
        "nei", "neo", "neu", "ni", "nia", "nie", "nio", "niu", "no", "noa", "noi", "nou", "nu",
        "nua", "nue", "nui", "nuo", "pa", "pae", "pai", "pao", "pau", "pe", "pea", "pei", "peo",
        "peu", "pi", "pia", "pie", "pio", "piu", "po", "poa", "poi", "pou", "pu", "pua", "pue",
        "pui", "puo", "qa", "qae", "qai", "qao", "qau", "qe", "qea", "qei", "qeo", "qeu", "qi",
        "qia", "qie", "qio", "qiu", "qo", "qoa", "qoi", "qou", "qu", "qua", "que", "qui", "quo",
        "ra", "rae", "rai", "rao", "rau", "re", "rea", "rei", "reo", "reu", "ri", "ria", "rie",
        "rio", "riu", "ro", "roa", "roi", "rou", "ru", "rua", "rue", "rui", "ruo", "sa", "sae",
        "sai", "sao", "sau", "se", "sea", "sei", "seo", "seu", "si", "sia", "sie", "sio", "siu",
        "so", "soa", "soi", "sou", "su", "sua", "sue", "sui", "suo", "ta", "tae", "tai", "tao",
        "tau", "te", "tea", "tei", "teo", "teu", "ti", "tia", "tie", "tio", "tiu", "to", "toa",
        "toi", "tou", "tu", "tua", "tue", "tui", "tuo", "va", "vae", "vai", "vao", "vau", "ve",
        "vea", "vei", "veo", "veu", "vi", "via", "vie", "vio", "viu", "vo", "voa", "voi", "vou",
        "vu", "vua", "vue", "vui", "vuo", "wa", "wae", "wai", "wao", "wau", "we", "wea", "wei",
        "weo", "weu", "wi", "wia", "wie", "wio", "wiu", "wo", "woa", "woi", "wou", "wu", "wua",
        "wue", "wui", "wuo", "xa", "xae", "xai", "xao", "xau", "xe", "xea", "xei", "xeo", "xeu",
        "xi", "xia", "xie", "xio", "xiu", "xo", "xoa", "xoi", "xou", "xu", "xua", "xue", "xui",
        "xuo", "za", "zae", "zai", "zao", "zau", "ze", "zea", "zei", "zeo", "zeu", "zi", "zia",
        "zie", "zio", "ziu", "zo", "zoa", "zoi", "zou", "zu", "zua", "zue", "zui", "zuo",
    ];
    static NAME4: [&str; 29] = [
        "a", "aa", "ae", "au", "ao", "ai", "e", "ee", "ea", "ei", "eo", "eu", "i", "ia", "io",
        "iu", "ie", "o", "oo", "ou", "oa", "oe", "oi", "u", "uu", "ua", "ue", "ui", "uo",
    ];
    static NAME5: [&str; 152] = [
        "rch", "ch", "r", "hs", "sum", "som", "sam", "sahm", "sohm", "suhm", "sir", "sihr", "sohr",
        "sor", "sur", "suhr", "sach", "rach", "roch", "rus", "rum", "ram", "rom", "rohm", "rahm",
        "ruhm", "run", "ran", "ron", "rin", "rihn", "rohn", "rohm", "rahn", "buhr", "bohr", "bihr",
        "bach", "bal", "bahl", "boch", "bahr", "bur", "bor", "bar", "buhn", "buhm", "bun", "bohn",
        "bon", "duhr", "dohr", "dal", "dahl", "dihr", "dach", "doch", "dahr", "dur", "dor", "dar",
        "duhn", "duhm", "dun", "dohn", "don", "muhr", "mohr", "mihr", "mach", "moch", "mahr",
        "mur", "mor", "mal", "mahl", "mar", "muhn", "muhm", "mun", "mohn", "mon", "nuhr", "nohr",
        "nihr", "nach", "noch", "nahr", "nur", "nor", "nar", "nuhn", "nuhn", "nun", "nohn", "non",
        "xuhr", "xohr", "xihr", "xach", "xoch", "xahr", "xur", "xor", "xar", "xuhn", "xuhm", "xun",
        "xohn", "xon", "zuhr", "zohr", "zihr", "zach", "zoch", "zahr", "zur", "zor", "zar", "zuhn",
        "zuhm", "zun", "zohn", "zon", "zal", "zahl", "xal", "xahl", "zhal", "zhor", "zhar", "bhal",
        "dhal", "xhar", "xhal", "luhr", "lohr", "lihr", "lach", "loch", "lahr", "lur", "lor",
        "lar", "luhn", "luhm", "lun", "lohn", "lon", "lhar", "lhan", "lham",
    ];
    static NAME6: [&str; 25] = [
        "br", "cr", "dr", "fr", "gr", "pr", "str", "tr", "bl", "cl", "fl", "gl", "pl", "sl", "sc",
        "sk", "sm", "sn", "sp", "st", "sw", "ch", "sh", "th", "wh",
    ];
    static NAME7: [&str; 10] = ["", "", "", "", "", "", "a", "e", "o", "u"];
    static NAME8: [&str; 71] = [
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "a", "aa",
        "ae", "au", "ao", "ai", "e", "ee", "ea", "ei", "eo", "eu", "i", "ia", "io", "iu", "ie",
        "o", "oo", "ou", "oa", "oe", "oi", "u", "uu", "ua", "ue", "ui", "uo",
    ];

    let rnd0 = rand_max(10);

    if rnd0 < 3 {
        let rnd1 = rand_max(NAME1.len());
        let rnd7 = rand_max(NAME7.len());
        let rnd5 = rand_max(NAME5.len());

        make_ascii_title_case(String::from(NAME1[rnd1]) + NAME7[rnd7] + NAME5[rnd5])
    } else if rnd0 < 6 {
        let rnd8 = rand_max(NAME8.len());
        let rnd3 = rand_max(NAME3.len());
        let rnd5 = rand_max(NAME5.len());

        make_ascii_title_case(String::from(NAME8[rnd8]) + NAME3[rnd3] + NAME5[rnd5])
    } else if rnd0 < 8 {
        let rnd6 = rand_max(NAME6.len());
        let rnd4 = rand_max(NAME4.len());
        let rnd5 = rand_max(NAME5.len());
        let rnd7 = rand_max(NAME7.len());

        make_ascii_title_case(String::from(NAME6[rnd6]) + NAME4[rnd4] + NAME5[rnd5] + NAME7[rnd7])
    } else {
        let rnd1 = rand_max(NAME1.len());
        let rnd7 = rand_max(NAME7.len());
        let rnd3 = rand_max(NAME3.len());
        let rnd5 = rand_max(NAME5.len());

        make_ascii_title_case(String::from(NAME1[rnd1]) + NAME7[rnd7] + NAME3[rnd3] + NAME5[rnd5])
    }
}

pub fn goblin(gender: NickGender) -> String {
    static NAME1: [&str; 45] = [
        "", "", "", "", "", "", "", "b", "c", "d", "f", "g", "h", "j", "k", "l", "p", "r", "t",
        "v", "w", "x", "z", "br", "bl", "cr", "cl", "ch", "dr", "fr", "gr", "gl", "gn", "kr", "kl",
        "pr", "pl", "str", "st", "sr", "sl", "tr", "vr", "wr", "zr",
    ];
    static NAME2: [&str; 24] = [
        "a", "e", "i", "o", "u", "a", "e", "i", "o", "u", "a", "e", "i", "o", "u", "y", "ia", "io",
        "ee", "aa", "ui", "ie", "ea", "oi",
    ];
    static NAME3: [&str; 156] = [
        "b", "d", "g", "h", "k", "l", "m", "n", "r", "s", "t", "v", "z", "b", "d", "g", "h", "k",
        "l", "m", "n", "r", "s", "t", "v", "z", "b", "d", "g", "h", "k", "l", "m", "n", "r", "s",
        "t", "v", "z", "b", "d", "g", "h", "k", "l", "m", "n", "r", "s", "t", "v", "z", "bb", "bd",
        "bh", "bl", "bk", "bn", "br", "bs", "bt", "bz", "db", "dd", "df", "dh", "dl", "dn", "dr",
        "ds", "dv", "dz", "", "gg", "gb", "gd", "gh", "gk", "gl", "gm", "gn", "gr", "gs", "gt",
        "gz", "hd", "hb", "hk", "hn", "hz", "kl", "kn", "kz", "kv", "kk", "lb", "ld", "lg", "lk",
        "ll", "lr", "ls", "lt", "lv", "lz", "mr", "mv", "mz", "mt", "nr", "nv", "nz", "nt", "rb",
        "rd", "rg", "rk", "rl", "rm", "rn", "rr", "rs", "rt", "rv", "rz", "sb", "sd", "sh", "sk",
        "sm", "sn", "sr", "str", "st", "sv", "sz", "ss", "tb", "tl", "tm", "tn", "tr", "tv", "tz",
        "tt", "vl", "vn", "vr", "vz", "zb", "zd", "zg", "zl", "zm", "zn", "zt",
    ];
    static NAME4: [&str; 34] = [
        "c", "g", "k", "l", "q", "r", "t", "x", "z", "nk", "ld", "rd", "s", "sz", "zz", "ng", "kz",
        "lb", "rm", "sb", "bs", "ts", "cs", "ct", "gs", "gz", "kt", "kx", "lk", "lx", "rk", "rt",
        "rd", "rx",
    ];
    static NAME5: [&str; 50] = [
        "", "", "", "", "", "", "", "b", "c", "d", "f", "g", "h", "j", "k", "l", "m", "n", "p",
        "q", "r", "s", "t", "v", "w", "bh", "br", "bl", "cr", "cl", "ch", "fr", "fl", "gr", "gl",
        "gn", "kh", "kl", "ph", "pr", "sh", "st", "sr", "sl", "sw", "th", "thr", "tr", "vr", "wr",
    ];
    static NAME6: [&str; 153] = [
        "b", "f", "g", "h", "k", "l", "m", "n", "p", "r", "s", "t", "v", "b", "f", "g", "h", "k",
        "l", "m", "n", "p", "r", "s", "t", "v", "b", "f", "g", "h", "k", "l", "m", "n", "p", "r",
        "s", "t", "v", "b", "f", "g", "h", "k", "l", "m", "n", "p", "r", "s", "t", "v", "bb", "bd",
        "bh", "bl", "bk", "bn", "br", "bs", "bt", "bz", "fb", "fl", "fm", "fn", "fs", "ft", "gg",
        "gb", "gd", "gh", "gk", "gl", "gm", "gn", "gr", "gs", "gt", "gz", "hd", "hb", "hk", "hn",
        "hz", "kl", "kn", "kz", "kv", "kk", "lb", "ld", "lg", "lk", "ll", "lr", "ls", "lt", "lv",
        "lz", "mr", "mv", "mz", "mt", "nr", "nv", "nz", "nt", "ph", "pf", "pl", "pn", "pm", "pr",
        "ps", "pt", "pv", "rb", "rd", "rg", "rk", "rl", "rm", "rn", "rr", "rs", "rt", "rv", "rz",
        "sb", "sd", "sh", "sk", "sm", "sn", "sr", "str", "st", "sv", "sz", "ss", "tb", "tl", "tm",
        "tn", "tr", "tv", "tz", "tt", "vl", "vn", "vr", "vz",
    ];
    static NAME7: [&str; 33] = [
        "h", "f", "g", "l", "n", "q", "s", "x", "z", "ls", "nk", "zz", "ld", "sh", "sz", "ss",
        "gs", "sx", "lx", "hx", "th", "rx", "rt", "ft", "fs", "fz", "lm", "lk", "lt", "ng", "nx",
        "ns", "nq",
    ];
    static NAME8: [&str; 20] = [
        "e", "i", "ee", "ia", "ea", "a", "ai", "", "", "", "", "", "", "", "", "", "", "", "", "",
    ];

    let rnd0 = rand_max(10);
    let rnd2 = rand_max(NAME2.len());
    let rnd2b = rand_max(NAME2.len());

    match gender {
        NickGender::Female => {
            let rnd5 = rand_max(NAME5.len());
            let rnd7 = rand_max(NAME7.len());
            let rnd8 = rand_max(NAME8.len());

            if rnd0 < 5 {
                make_ascii_title_case(
                    String::from(NAME5[rnd5]) + NAME2[rnd2] + NAME7[rnd7] + NAME8[rnd8],
                )
            } else {
                let rnd6 = rand_max(NAME6.len());

                make_ascii_title_case(
                    String::from(NAME5[rnd5])
                        + NAME2[rnd2]
                        + NAME6[rnd6]
                        + NAME2[rnd2b]
                        + NAME7[rnd7]
                        + NAME8[rnd8],
                )
            }
        }
        NickGender::Male => {
            let rnd1 = rand_max(NAME5.len());
            let rnd4 = rand_max(NAME7.len());

            if rnd0 < 5 {
                make_ascii_title_case(String::from(NAME1[rnd1]) + NAME2[rnd2] + NAME4[rnd4])
            } else {
                let rnd3 = rand_max(NAME3.len());

                make_ascii_title_case(
                    String::from(NAME1[rnd1])
                        + NAME2[rnd2]
                        + NAME3[rnd3]
                        + NAME2[rnd2b]
                        + NAME4[rnd4],
                )
            }
        }
    }
}

#[cfg(test)]
mod test {
    use super::*;

    #[test]
    fn test_all_generators_returns_non_empty_nickname() {
        assert!(!dwarf(NickGender::Female).is_empty());
        assert!(!dwarf(NickGender::Male).is_empty());

        assert!(!barbarian(NickGender::Female).is_empty());
        assert!(!barbarian(NickGender::Male).is_empty());

        assert!(!elf(NickGender::Female).is_empty());
        assert!(!elf(NickGender::Male).is_empty());

        assert!(!bandit(NickGender::Female).is_empty());
        assert!(!bandit(NickGender::Male).is_empty());

        assert!(!goblin(NickGender::Female).is_empty());
        assert!(!goblin(NickGender::Male).is_empty());

        assert!(!demon().is_empty());

        assert!(!random_name().is_empty());
    }

    fn firstname_and_lastname_start_from_upper_letters(name: &str) -> bool {
        let mut names = name.split(" ");
        let valid_first_name = names
            .next()
            .unwrap_or("invalid_name")
            .chars()
            .next()
            .unwrap_or('n')
            .is_ascii_uppercase();

        let valid_lastname = if names.clone().count() > 0 {
            names
                .next()
                .unwrap_or("invalid_lastname")
                .chars()
                .next()
                .unwrap_or('n')
                .is_ascii_uppercase()
        } else {
            true
        };

        valid_first_name && valid_lastname
    }

    #[test]
    fn test_all_names_start_from_upper_letter() {
        assert!(firstname_and_lastname_start_from_upper_letters(&dwarf(
            NickGender::Female
        )));
        assert!(firstname_and_lastname_start_from_upper_letters(&dwarf(
            NickGender::Male
        )));

        assert!(firstname_and_lastname_start_from_upper_letters(&barbarian(
            NickGender::Female
        )));
        assert!(firstname_and_lastname_start_from_upper_letters(&barbarian(
            NickGender::Male
        )));

        assert!(firstname_and_lastname_start_from_upper_letters(&elf(
            NickGender::Female
        )));
        assert!(firstname_and_lastname_start_from_upper_letters(&elf(
            NickGender::Male
        )));

        assert!(firstname_and_lastname_start_from_upper_letters(&bandit(
            NickGender::Female
        )));
        assert!(firstname_and_lastname_start_from_upper_letters(&bandit(
            NickGender::Male
        )));

        assert!(firstname_and_lastname_start_from_upper_letters(&goblin(
            NickGender::Female
        )));
        assert!(firstname_and_lastname_start_from_upper_letters(&goblin(
            NickGender::Male
        )));

        assert!(firstname_and_lastname_start_from_upper_letters(&demon()));

        assert!(firstname_and_lastname_start_from_upper_letters(
            &random_name()
        ));
    }
}
